### ISSUE TITLE
App icons like action icons in small resolution

### ISSUE THREAD

**Issue by ceyhunnabiyev** [gusbemacbe/suru-plus#101]
Suru:
![screenshot from 2019-03-05 21-01-13](https://user-images.githubusercontent.com/5506156/53822775-d6e65700-3f89-11e9-8c46-3cc35cac6dec.png)

Papirus:
![screenshot from 2019-03-04 12-12-49](https://user-images.githubusercontent.com/5506156/53822797-dfd72880-3f89-11e9-832c-e2cd68150a3f.png)

**Comment by gusbemacbe** [comment]
Hi @ceyhunnabiyev!

The 16px and 24px icons are monochromatic. If you want 16px and 24px to be colorful, you can force to symlink (`ln -sfnr`) from the folder `64` to the folders `16` and `24`.

If you want the light icons, please use [Suru++ Dark](https://github.com/gusbemacbe/suru-plus-dark).

**Comment by ceyhunnabiyev** [comment]
Thank you for the info..
