### ISSUE TITLE
AUR package doesn't build

### ISSUE THREAD

**Issue by materemias** [gusbemacbe/suru-plus#103]
the latest update keeps building with every update.

**Comment by gusbemacbe** [comment]
Hi @materemias !

I will investigate.

**Comment by gusbemacbe** [comment]
The cause was `pkgver=25.2.0`, I have replaced for `pkgver=25.2` because in the list of releases in this repositories, the package was tagged as `v25.2`.

**Comment by gusbemacbe** [comment]
I have fixed it. See if it works for you.

**Comment by materemias** [comment]
it is working properly, thanks for the quick fix!
