### ISSUE TITLE
elementary os panel

### ISSUE THREAD

**Issue by Chamrosh** [gusbemacbe/suru-plus#105]
epapirus:
![screenshot from 2019-03-07 18 14 57](https://user-images.githubusercontent.com/10561726/53964652-fc4ba000-4104-11e9-9a4d-03fd09069bb2.png)

suru++
![screenshot from 2019-03-07 18 13 36](https://user-images.githubusercontent.com/10561726/53964670-053c7180-4105-11e9-9bd5-c4ef9f12a5b3.png)

**Comment by gusbemacbe** [comment]
Hi @Chamrosh, I will investigate the icon size bug.

**Comment by gusbemacbe** [comment]
I understood now. Suru++ 25 must be well appropriate with more than 11 desktop environment, but not with elementary OS. I will consider creating eSuru++.

**Comment by gusbemacbe** [comment]
Hi @Chamrosh !

I have just added eSuru++.

As you have already installed Suru++, please add eSuru++, running the command:

```bash
wget -qO- https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/install.sh | TAG=beta THEMES=eSuru++ sh
```

**Comment by gusbemacbe** [comment]
Please, check if they work on your elementary OS's panel.

**Comment by Chamrosh** [comment]
It's great
Thank you

**Comment by gusbemacbe** [comment]
As it is solved, it will be closed.
