### ISSUE TITLE
question about color-picker-black.svg icon

### ISSUE THREAD

**Issue by roachsinai** [gusbemacbe/suru-plus#106]
After I set kde panel to transparent, icon like `todour` #98 worked great! But `color-picker-black.svg` icon which is located at `Suru++/actions/16/color-picker-black.svg` not work means it hard to find it.

icon todour and others worked icons:
![image](https://user-images.githubusercontent.com/9500049/54106561-8c455e80-4411-11e9-83ec-8bfb16fe77f4.png)

icon color-picker-black.svg:
![image](https://user-images.githubusercontent.com/9500049/54106760-1db4d080-4412-11e9-90d2-0d3f53565534.png)

icon color-picker-black.svg hovered:
![image](https://user-images.githubusercontent.com/9500049/54106792-37561800-4412-11e9-9676-e5c6a5acdd38.png)

When the icon not hovered it's so hard to find it.

**Comment by roachsinai** [comment]
And breeze icon could show it more brighter no hover.
![image](https://user-images.githubusercontent.com/9500049/54107674-c9f7b680-4414-11e9-8e0e-40caf48b10fd.png)

**Comment by gusbemacbe** [comment]
Yes, because of `-black` , I'll reconsider it.

**Comment by roachsinai** [comment]
> Yes, because of `-black` , I'll reconsider it.

Oh, the `-black` means if panel be black it will turn `white`?

**Comment by gusbemacbe** [comment]
Yes, if you pick the black colour, the picker will turn black, and if you pick the white colour, the picker will turn white. 

We have color-picker-blue and color-picker-red. 

Tonight I'll check the color-picker icons of Breeze.

**Comment by roachsinai** [comment]
Okay, thanks.

**Comment by gusbemacbe** [comment]
Hello @roachsinai !

I have checked the Breeze icons, it keeps the black colour with a black colour, and on Breeze Dark, with a white stroke. Then I added a FitDance-coloured gradient stroke for you to distinguish the colour-picker if the black ink is picked. 

Breeze icons:

![imagem](https://user-images.githubusercontent.com/2257024/54471047-5e557680-4791-11e9-88c8-a8f2caeee7b8.png)

Breeze Dark icons:

![imagem](https://user-images.githubusercontent.com/2257024/54471051-775e2780-4791-11e9-98b8-ac288340b856.png)

To test, please run the command:

```
wget -qO- https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/install.sh | TAG=beta THEMES=Suru++ sh
```

**Comment by roachsinai** [comment]
Thanks for a lot!!!
