### ISSUE TITLE
[Bug] xfce4-panel status notifier plugin

### ISSUE THREAD

**Issue by sptndc** [gusbemacbe/suru-plus#107]
![Screenshot_2019-03-11_22-54-17](https://user-images.githubusercontent.com/20803810/54137679-a6eaf800-4450-11e9-916b-89debeb1f360.png)

**Comment by gusbemacbe** [comment]
Hello @sptndc 

Please download the beta branch and instal both eSuru++ and Suru++, using the commands:

```
wget -qO- https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/install.sh | TAG=beta THEMES=Suru++ sh
wget -qO- https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/install.sh | TAG=beta THEMES=eSuru++ sh
```

Test with both eSuru++ and Suru++.

**Comment by sptndc** [comment]
@gusbemacbe thanks for your response.

But there have been no changes for this issue.
I think this reference can fix this issue keeferrourke/la-capitaine-icon-theme#411

**Comment by gusbemacbe** [comment]
Are you referring to the light or black icons in the status panel?

**Comment by sptndc** [comment]
Black icons for light panel.

**Comment by gusbemacbe** [comment]
Then the white icons need to be black. I'll study the references. 

Please test @SmartFinn's Papirus and see if it has the same problem, because some icons have been derived of them.

**Comment by sptndc** [comment]
This is a screenshot of the Papirus-Light icons.

![Screenshot_2019-03-14_22-10-20](https://user-images.githubusercontent.com/20803810/54368188-448b3500-46a6-11e9-85be-b38c9c222a72.png)

**Comment by gusbemacbe** [comment]
I got it now! Then I did not create Suru++ Light. 

Although Suru++ be compatible with more than 11 environments, it is not well appropriate for certain environments. Therefore, I have created eSuru++ for elementary OS. I'll create Suru++ Light. I have created Suru++ Dark, but for full dark environment.

**Comment by sptndc** [comment]
Okay, thanks for your hard work.

**Comment by gusbemacbe** [comment]
Hello @sptndc 

Please install Suru++ Light:

```
wget -qO- https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/install.sh | TAG=beta THEMES=Suru++-Light sh
```

**Comment by sptndc** [comment]
This is great! it's just that the Blueman Bluetooth Manager and Gigolo icons are less attractive.

| Blueman Bluetooth Manager | Gigolo |
| ----------- | ----------- |
| ![Blueman-Bluetooth-Manager](https://user-images.githubusercontent.com/20803810/54473448-70bfc680-480a-11e9-8ab4-55ccd92c3bfb.png) | ![Gigolo](https://user-images.githubusercontent.com/20803810/54473461-90ef8580-480a-11e9-86c4-73f180f469e0.png) |

**Comment by sptndc** [comment]
@gusbemacbe Okay, thanks!

**Comment by gusbemacbe** [comment]
After tell me if they worked.

**Comment by sptndc** [comment]
It's worked great!

**Comment by gusbemacbe** [comment]
Great. Issue closed.
