### ISSUE TITLE
Add vnote and listen1 icons

### ISSUE THREAD

**Issue by roachsinai** [gusbemacbe/suru-plus#108]
Could you please add icons for:

+ VNote refer at https://github.com/tamlok/vnote/blob/master/src/resources/icons/vnote.ico
+ listen1 refer at https://github.com/listen1/listen1_desktop/blob/master/app/resources/logo_16.png

**Comment by gusbemacbe** [comment]
Added. Please update, using that same command in another issue.

**Comment by roachsinai** [comment]
Thanks! May I asked one more question?

Like `vnote` icon, the origin is located in theme `hicolor`. 

After I launch `vnote` application, there is a `vnote` icon in system tray with `hicolor` theme one used.

Is there a way to let system tray use `Suru++` theme one? Without use `Suru++` icon override the icon of `hicolor`.

**Comment by gusbemacbe** [comment]
It means that vnote's desktop file does not have icon code, or is using the fixed icon path or icon generic name. Please, check:

* https://github.com/gusbemacbe/suru-plus/tree/beta#hardcoded-application-icons-with-ugly-name

You need to modify manually the vnote's desktop file at `/usr/share/applications` or `~/.local/share/applications`.

**Comment by roachsinai** [comment]
desktop file for `listen1`

```
[Desktop Entry]
Name=Listen1
Comment=One for all free music in China
Exec=env DESKTOPINTEGRATION=no "/opt/appimages/listen1.AppImage" %U
Terminal=false
Type=Application
Icon=listen1
StartupWMClass=Listen1
X-AppImage-Version=2.1.5
Categories=Utility;
X-AppImage-BuildId=1HvKDJ3EUJMJwm6YxKB8wQfQx3p
```

But I got the original icon:

![image](https://user-images.githubusercontent.com/9500049/54471909-7eba1b00-47fb-11e9-906c-c6309f5f091c.png)

Maybe the reason is that `listen1` is a `appimage` application?

**Comment by gusbemacbe** [comment]
Yes, AppImageLaunche creates the desktop file automatically. If you modify again, AppImageLaunches will revert when you open the AppImage. Please check:

https://github.com/gusbemacbe/suru-plus/tree/beta#appimage-built-apps

**Comment by roachsinai** [comment]
Thanks for you instructions!

My `listen1.desktop` file content at `/usr/share/applications` and `/home/roach/.local/share/applications`:

```
[Desktop Entry]
Name=Listen1
Comment=One for all free music in China
Exec=env DESKTOPINTEGRATION=no "/opt/appimages/listen1.AppImage" %U
Terminal=false
Type=Application
Icon=listen1
StartupWMClass=listen1
X-AppImage-Version=2.1.5
Categories=Utility;
X-AppImage-BuildId=1HvKDJ3EUJMJwm6YxKB8wQfQx3p
```

I have removed `appimagelauncher` and rebooted. But, still not work.

---

btw, `sudo StartupWMClassFixer` is not work for https://github.com/bilelmoussaoui/StartupWMClassFixer, have to use `sudo /opt/StartupWMClassFixer/fix`.

**Comment by gusbemacbe** [comment]
Change `StartupWMClass=listen1` to `StartupWMClass=Listen1` because of `Name` given to an AppImage. 

Remove `X-AppImage-Version=2.1.5` and `X-AppImage-BuildId=1HvKDJ3EUJMJwm6YxKB8wQfQx3p`. 

Change `Exec=env DESKTOPINTEGRATION=no "/opt/appimages/listen1.AppImage" %U` to `Exec=/opt/appimages/listen1.AppImage`. As AppImageLauncher is removed, no need to keep `env DESKTOPINTEGRATION=no`.

**Comment by gusbemacbe** [comment]
After finishing, you need to update the database cache in the terminal if you do not want to reboot again.

**Comment by roachsinai** [comment]
Hi, @gusbemacbe 

Seems don't know what's wrong.

```
hmank ~ > cat .local/share/applications/listen1.desktop 
[Desktop Entry]
Name=Listen1
Comment=One for all free music in China
Exec=/opt/appimages/listen1.AppImage
Terminal=false
Type=Application
Icon=listen1
StartupWMClass=Listen1
Categories=Utility;
hmank ~ > ll /usr/share/icons/Suru++/apps/16 | grep listen
-rw-r--r-- 1 root root 2.7K 3月  16 14:04 listen1.svg
```

**Comment by roachsinai** [comment]
And should I use `sudo gtk-update-icon-cache /usr/share/icons/Suru++`  to update cache no need reboot?

**Comment by gusbemacbe** [comment]
Yes, it generates the new icon cache to remove old cache. 

You can use Stacer to clean the old caches of icons and of desktop files without needing to reboot.

**Comment by gusbemacbe** [comment]
Maybe of `Exec=/opt/appimages/listen1.AppImage`, because it is rooted.

**Comment by roachsinai** [comment]
I've move it to other places. But not work, too.

But, thanks a lot for the help so far.

**Comment by gusbemacbe** [comment]
Tonight I'll test Listen1. I'm at college now.

**Comment by roachsinai** [comment]
That's great!!!

**Comment by gusbemacbe** [comment]
Hi @roachsinai !

It worked here, and I will send a zipped desktop. 

![imagem](https://user-images.githubusercontent.com/2257024/54483093-ec326f80-482c-11e9-812f-2612418f60ea.png)

1. Create the folder `Applications/AppImages` in your home folder.
2. Move AppImage to the `~/Applications/AppImages/` 
3. Rename the AppImage `listen1` to `Listen1`. Make it executable and trusting, using the command `chmod a+x Listen1.AppImage`.
4. Extract the zip, open the desktop file and change `/data/Gustavo/Applications/AppImage/Listen1.AppImage` to `$HOME/Applications/AppImages/Listen1.AppImage`
5. Move the desktop file to `~/.local/share/applications/`
6. Ready. 

[Listen1.tar.gz](https://github.com/gusbemacbe/suru-plus/files/2974612/Listen1.tar.gz)

**Comment by roachsinai** [comment]
Hi, does the icon shows on system tray is located at `Suru++/panel`?

As I found `vnote` and `dropbox` svg at `Suru++/apps` is 
![Screenshot_20190317_100643](https://user-images.githubusercontent.com/9500049/54484290-1ec88080-489e-11e9-89c8-863e79442af1.png)

But, `dropbox` color could be white at tray

![image](https://user-images.githubusercontent.com/9500049/54484295-3acc2200-489e-11e9-8a46-add169b3d164.png)

And, last I found there is `dropboxstatus-idle.svg` under `Suru++/panel/16`.

**Comment by gusbemacbe** [comment]
@roachsinai 

Do not `apps` with `panel`. The `dropbox.svg` and `vnote.svg` of `apps` is for applications icons and not for Dropbox and VNote status panel icon. 

> Hi, does the icon shows on system tray is located at Suru++/panel?

It does not have VNote status icon. I need to download VNote and find the icons.

**Comment by gusbemacbe** [comment]
Then icons are `vnote_ink`, `vnote_small` and `vnote_update`, according to https://github.com/tamlok/vnote/tree/master/src/resources/icons. I will add to `panel`.

**Comment by gusbemacbe** [comment]
Hi @roachsinai 

Added. 

Run the command:

```
wget -qO- https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/install.sh | TAG=beta sh
```

**Comment by roachsinai** [comment]
Thanks!!!
