### ISSUE TITLE
elementary os icon bug

### ISSUE THREAD

**Issue by Chamrosh** [gusbemacbe/suru-plus#109]
mail app
![Screenshot from 2019-03-11 21 18 23](https://user-images.githubusercontent.com/10561726/54145715-c4659500-4443-11e9-97d2-6236f64d7bb6.png)

code
![Screenshot from 2019-03-11 21 18 49](https://user-images.githubusercontent.com/10561726/54145725-c92a4900-4443-11e9-86c1-3dd743d4291c.png)

photos
![Screenshot from 2019-03-11 21 19 12](https://user-images.githubusercontent.com/10561726/54145731-cd566680-4443-11e9-98c2-2aa4e885c72a.png)

**Comment by gusbemacbe** [comment]
These colorful icons are 32px. Other monochromatic icons are 24px. The eSuru++ inherits from Suru++. 

I have to modify eSuru++.

**Comment by gusbemacbe** [comment]
HI @Chamrosh 

Firstly you update Suru++ and then eSuru++, run in the terminal:

```
wget -qO- https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/install.sh | TAG=beta THEMES=Suru++ sh
wget -qO- https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/install.sh | TAG=beta THEMES=eSuru++ sh
```

See if it works.

**Comment by Chamrosh** [comment]
![Screenshot from 2019-03-13 20 07 54](https://user-images.githubusercontent.com/10561726/54297497-4385d500-45cc-11e9-9eaf-18f0d91325f3.png)

**Comment by gusbemacbe** [comment]
@Chamrosh 

I will install elementary OS Code app on Manjaro to investigate the icons.

**Comment by gusbemacbe** [comment]
@SmartFinn !

What is the name of this blue folder with magnifying glass icon in your icons theme ePapirus?

![imagem](https://user-images.githubusercontent.com/2257024/54316331-38787800-45bf-11e9-9f2c-3963d4c05d1d.png)

**Comment by SmartFinn** [comment]
@gusbemacbe `folder-saved-search`

**Comment by gusbemacbe** [comment]
@SmartFinn Strange, the `folder-saved-search.svg` that I found on my icons themes, is not wrong, so it is a folder with glass and not only a glass.

**Comment by gusbemacbe** [comment]
@Chamrosh 

I finally figured the icon. It was in the eSuru++, copeid from ePapirus. The icon of both eSuru++ and ePapirus was wrong. I fixed. Please update, using the same commands above. 

I will alert @SmartFinn ans @varlesh.

In ePapirus, in the folders 16, 22 and 24, the icon` folder-search.svg` is wrong, so in the elementary OS Code app, the colourful icon of `folder-search.svg` is shown instead of monochromatic icon. But if I resymlink 16 to 22 and 24, there will be two same magnifying glass icons in the elementary OS Code app.

You need to redesign the icon. A folder with magnifying glass and not just a magnifying glass.

**Comment by SmartFinn** [comment]
@gusbemacbe I added a workaround for the icon before https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1510 and now I see that is not working. To make it display correctly I have to remove `folder-saved-search` from places and left it in actions, but I don't sure that is right.

**Comment by gusbemacbe** [comment]
@SmartFinn 

Then in the `ePapirus/16x16/places/`, it does not have `folder-search.svg` which seems to be a new icon of elementary OS Code app. 

Ah, I got,

`ePapirus/22x22/places` is symlinked to `Papirus/22x22/places` which is colourful. You need to resymlink `ePapirus/16x16/places/` to `ePapirus/22x22/places/`. If it does not work, keep that, then  also resymlink to `ePapirus/24x24/places/`

Do not forget of adding the `folder-search.svg` in the 22, 24, 32, 48 and 64 folders.

**Comment by SmartFinn** [comment]
@gusbemacbe there no `folder-search` icon, it's `folder-saved-search`

https://github.com/elementary/code/blob/1b5ffc5468e61791a88bddf7391d5265be2458f1/src/Widgets/HeaderBar.vala#L46
https://github.com/elementary/code/blob/e0f239f11ed928907e0661f6a39727447803a4eb/src/Widgets/WelcomeView.vala#L34


> You need to resymlink `ePapirus/16x16/places/` to `ePapirus/22x22/places/`

It's a dirty hack, we don't use it.

**Comment by gusbemacbe** [comment]
Ok, @SmartFinn, maybe better let @codygarver, @roymckenzie and @danrabbit. They may have knowledge of this problem.
