### ISSUE TITLE
Update ffsvg wanted

### ISSUE THREAD

**Issue by gusbemacbe** [gusbemacbe/suru-plus#110]
Hello @SmartFinn !

I am not expert in Bash and in Python.

The problem is that `ffsvg` will remove the list of 9 gradients and will shorten #ffffff to #fff. 

I would like to preserve the gradients list and the 6 numbers of colour hexadecimal code. And I would like `ffsvg` convert #UPPERCASE-COLOURS to #lowercase-colours. 

Is there way to update it?

**Comment by SmartFinn** [comment]
But `ffsvg` can't do this. You can check it by running:

```
cd scripts/
./ffsvg.svg list-colours.svg
git difftool
```

The hex codes are left as is and the gradients are not removed. I suppose the changes are made by your editor.

**Comment by gusbemacbe** [comment]
> The hex codes are left as is and the gradients are not removed. I suppose the changes are made by your editor.

I did a test. The `ffsvg` did not remove the gradients of `list-colours.svg`, but removed the gradients of a new SVG icon test.

**Comment by SmartFinn** [comment]
How can I reproduce it? Could you upload the icon that will be broken with ffsvg?

**Comment by gusbemacbe** [comment]
Hi, @SmartFinn 

Ready. You can test with the icon `listen1.svg` which contains 9 gradients list.

**Comment by SmartFinn** [comment]
No gradients are removed. Do you use `svgo` or `scour`? Try to update `svgo` to the latest version `npm install -g svgo`

**Comment by SmartFinn** [comment]
I got it. `scour` removes the gradients. Just install `svgo` using the command above. We don't use `scour` in our projects, it added like a fallback for new contributors.

**Comment by gusbemacbe** [comment]
Ah, I used both `scour` and `svgo` manually. I installed globally, and I tested, and the gradients are not removed. I have to keep one plugin globally and not manually. 

Thank you!

**Comment by gusbemacbe** [comment]
Hello @SmartFinn !

Please, can you update `install.sh`, for not just downloading Suru++, but also eSuru++ and Suru++-Light?

I am afraid of damaging the file.

**Comment by SmartFinn** [comment]
@gusbemacbe just change the line https://github.com/gusbemacbe/suru-plus/blob/master/install.sh#L8 to `: "${THEMES:=Suru++ Suru++-Light eSuru++}"`
