### ISSUE TITLE
Icon theme "Yaru" not found.

### ISSUE THREAD

**Issue by roachsinai** [gusbemacbe/suru-plus#111]
Hi, does `Suru++` have something related to `yaru`? When using this command, `wget -qO- https://raw.githubusercontent.com/gusbemacbe/suru-plus/beta/install.sh | TAG=beta sh`.

```
hmank ~/./s/f/t/simple master > dolphin .
Icon theme "Yaru" not found.

```

**Comment by gusbemacbe** [comment]
Hi @roachsinai 

It is `Inherits=Yaru,breeze,gnome,hicolor` in the file `index.theme`. An user of Ubuntu asked me to add Yaru to `Inherits`.

It is a normal error and unharmful, because you do not install Yaru icons, but you do not need to install it.

**Comment by roachsinai** [comment]
Got it. Thanks for reply.
