### ISSUE TITLE
Missing icons to add

### ISSUE THREAD

**Issue by xzj8b3** [gusbemacbe/suru-plus#113]
Missing icons Devede,DVD95,Onionshare,ophcrack if you can add them you complete the work

And maybe a more similar icon to the others for PDF files 

Really beautiful!!!!!

**Comment by gusbemacbe** [comment]
Ciao @xzj8b3 !

Abbiamo già le icone [Devede](https://github.com/gusbemacbe/suru-plus/blob/master/Suru++/apps/64/devede.svg) e [DVD95](https://github.com/gusbemacbe/suru-plus/blob/master/Suru++/apps/64/dvd95.svg). 

Se hai installato Devede e DVD95 via AppImage o Flatpak o Snap, ne hai bisogno di modificare manualmente i file di desktop di configurazione. Vedi https://github.com/gusbemacbe/suru-plus#known-bugs. 

Questa settimana, aggiungerò le icone di Onionshare e Ophrcrack.

**Comment by xzj8b3** [comment]
> Ciao @ xzj8b3 !
> 
> Abbiamo già le icone [Devede](https://github.com/gusbemacbe/suru-plus/blob/master/Suru++/apps/64/devede.svg) e [DVD95](https://github.com/gusbemacbe/suru-plus/blob/master/Suru++/apps/64/dvd95.svg) .
> 
> Se hai installato Devede e DVD95 via AppImage o Flatpak o Snap, ne hai bisogno di modificare manualmente i file di desktop di configurazione. Vedi https://github.com/gusbemacbe/suru-plus#known-bugs .
> 
> Questa settimana, aggiungerò le icone di Onionshare e Ophrcrack.

I installed normally from dnf but DevedeveNG and DVD95 icons remain those of defaulth that clash with the rest

However congratulations splendid themes

**Comment by gusbemacbe** [comment]
Grazie, @xzj8b3 !

Vai al `~/.local/share/applications` o `/usr/share/applications`, apri i file Devede e DVD95 con l'edittore di testo, copiane tutto e incollane qui, per io vedere.

**Comment by xzj8b3** [comment]
> Grazie, @ xzj8b3 !
> 
> Vai al `~/.local/share/applications`o `/usr/share/applications`, apri i file Devede e DVD95 con l'editore di testo, copiane tutto e incollane qui, per io vedere.

[Desktop Entry]
Name=Dvd95
Comment=DVD9 to DVD5 converter
Comment[fr]=Convertisseur DVD9 vers DVD5
Exec=dvd95
Icon=/usr/share/pixmaps/dvd95/dvd9548.png
Terminal=false
Type=Application
Categories=AudioVideo;X-OutputGeneration;


[Desktop Entry]
X-MultipleArgs=false
Type=Application
Name=DevedeNG
GenericName=DVD/CD Video Creator
X-GNOME-FullName=DevedeNG DVD/CD Video Creator
X-GNOME-FullName[ca]=DevedeNG creador de CD/DVDs de vídeo
X-GNOME-FullName[es]=DevedeNG creador de CD/DVDs de vídeo
X-GNOME-FullName[gl]=DevedeNG creador de CD/DVDs de vídeo
X-GNOME-FullName[pl]=DevedeNG tworzenie wideo na CD/DVD
X-GNOME-FullName[it]=DevedeNG creatore di video CD/DVD
Comment=Allows to create video CDs and DVDs, suitable to be reproduced in home DVD players
Comment[ca]=Permet crear CDs i DVDs de vídeo, que poden reproduir-se en reproductors domèstics
Comment[es]=Permite crear video CDs y DVDs, que pueden reproducirse en reproductores domésticos
Comment[gl]=Permite crear video CDs e DVDs, que poden reproducirse en reproductores domésticos
Comment[pl]=Pozwala stworzyć wideo na płytach CD lub DVD, do otwarzania w domowych odtwarzaczach DVD
Comment[it]=Permette di creare video CD e DVD che possono essere riprodotti con lettori DVD
Icon=devedeng_icon.svg
TryExec=devede_ng.py
Exec=devede_ng.py
Categories=AudioVideo;X-OutputGeneration;
X-Desktop-File-Install-Version=0.23

**Comment by gusbemacbe** [comment]
Ciao @xzj8b3 

```
Icon=/usr/share/pixmaps/dvd95/dvd9548.png
Icon=devedeng_icon.svg
```
Questi percorsi di queste icone delle app sono predefiniti o fissamente codificati (hardcoded). Hai bisogno di modificare manualmente così come:

```
Icon=dvd9548
Icon=devedeng_icon
```

o

```
Icon=dvd95
Icon=devede
```

Ricordati che hai bisogno di modificarli come root.

**Comment by gusbemacbe** [comment]
Hanno funzionato bene per te, @xzj8b3?

**Comment by xzj8b3** [comment]
> Hanno funzionato bene per te, @ xzj8b3 ?

It has to be changed 

DVD95 doesn't see it in any way.

**Comment by xzj8b3** [comment]
> > Hanno funzionato bene per te, @ xzj8b3?
> 
> Deve essere cambiato
> 
> DVD95 non lo vede in alcun modo.

dvd9548

**Comment by xzj8b3** [comment]
> > Hanno funzionato bene per te, @ xzj8b3?
> 
> Deve essere cambiato
> 
> DVD95 non lo vede in alcun modo.

Ok succeeded ..... I will report any new icons if it's not disturbing ..... it would be nice to have the package more and more complete seen as well as being very elegant is also among the most complete!!!

**Comment by gusbemacbe** [comment]
Hi @xzj8b3 

I have already the icon with the name of `dvd9548`, but I will add the icon with the name of `devedeng_icon`.

**Comment by xzj8b3** [comment]
> have already the icon with the name of `dvd9548`, but I will add the icon with the name of `devedeng_icon`.

Great, remember PDF icons 

[IMG]http://i66.tinypic.com/2sb75hj.jpg[/IMG]

It would be the TOP to be able to replace also manual icons etc. visible in the shell

OnionShare Ophcrack and if I notice any more in the future I will point out....

Congratulations again wonderful work!!!!!

**Comment by gusbemacbe** [comment]
> Great, remember PDF icons

It is a mimetype icon. You need to copy the desktop file text of that mimetype icon at the `~/usr/share/applications/Dive into Python.desktop
`
> [IMG]http://i66.tinypic.com/2sb75hj.jpg[/IMG]

GitHub uses Markdown instead of BBCode. Here is the same tutorial: https://riptutorial.com/it/markdown (in italiano)

```md
Invece di [img]https://git.io/image.png[/img]
Ecco:
![descrizione dell'immagini](https://git.io/image.png)
```

**Comment by xzj8b3** [comment]
> > Ottimo, ricorda le icone PDF
> 
> È un'icona mimetype. È necessario copiare il testo del file desktop di quell'icona di tipo mimetype sul`~/usr/share/applications/Dive into Python.desktop `
> 
> > [IMG] [http://i66.tinypic.com/2sb75hj.jpg[/IMG]](http://i66.tinypic.com/2sb75hj.jpg%5B/IMG%5D)
> 
> GitHub utilizza Markdown invece di BBCode. Ecco lo stesso tutorial: https://riptutorial.com/it/markdown (in italiano)
> 
> ```lisp
> Invece di [img] https://git.io/image.png [/ img]
> Ecco:
> ! [descrizione dell'immagini] (https://git.io/image.png)
> ```

[Desktop Entry]
Name=Dive Into Python
Comment=Open Dive Into Python book
Exec=xdg-open /usr/share/doc/diveintopython//pdf/diveintopython.pdf
Icon=gnome-mime-application-pdf
Terminal=false
Type=Application
Categories=Application;Development;Documentation;
X-Desktop-File-Install-Version=0.23

**Comment by gusbemacbe** [comment]
Hi,

I will add the icon `gnome-mime-application-pdf` as an app icon. Temporarily change from `gnome-mime-application-pdf` to `adobe-reader.svg`.

**Comment by xzj8b3** [comment]
> Ciao,
> 
> Aggiungerò l'icona `gnome-mime-application-pdf`come icona di un'app. Cambia temporaneamente da `gnome-mime-application-pdf`a `adobe-reader.svg`.

TENKS

**Comment by xzj8b3** [comment]
> > Ciao,
> > Aggiungerò l'icona `gnome-mime-application-pdf`come icona di un'app. Cambia temporaneamente da `gnome-mime-application-pdf`a `adobe-reader.svg`.
> 
> TENKS

https://extensions.gnome.org/extension/1230/gmail-message-tray/

Please add a light icon of the received emails displayed with that extension (a small dark email icon appears and you don't see it)

And although you can a more pleasant icon of "application settings" also displayed in Dash to Dock https://extensions.gnome.org/extension/307/dash-to-dock/

That would be great thanks in advance!!!!

**Comment by gusbemacbe** [comment]
Quando io sarò finito con il [Suru++ Ubuntu](https://github.com/Bonandry/suru-plus-ubuntu) dell'italiano @Bonandry, lavorerò con ciò.

**Comment by xzj8b3** [comment]
> Quando io sarò finito con il [Suru ++ Ubuntu](https://github.com/Bonandry/suru-plus-ubuntu) dell'italiano @Bonandry , lavorerò con ciò.

Excellent thanks

**Comment by gusbemacbe** [comment]
Ciao @!

Como sono finito con il repositorio [Suru++ Ubuntu](https://github.com/Bonandry/suru-plus-ubuntu), vado cominciare a lavorare con questo repositorio.

Aggiunte icone adesso.

**Comment by gusbemacbe** [comment]
@xzj8b3, the Onionshare icon has been added. I will Ophcrack icon.

**Comment by gusbemacbe** [comment]
Aggiunta l'icona Ophcrack, @xzj8b3. Pronto.

**Comment by xzj8b3** [comment]
> Aggiunta l'icona Ophcrack, @xzj8b3. Pronto.

Thank you very much, tomorrow or how can I update them and I will tell you .... Thank you again!!!

**Comment by gusbemacbe** [comment]
Come le icone aggiunte stanno sulla versione `beta`, esegui il commando nel terminale:

```
wget -qO- https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/install.sh | TAG=beta sh
```

**Comment by xzj8b3** [comment]
> wget -qO- https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/install.sh | TAG=beta sh

Exceptional ...

**Comment by gusbemacbe** [comment]
@xzj8b3 

You can write in Italian if you want. I have release a wiki in Italian. You can check "wiki" in the guides at the top of this GitHub repository page.
