### ISSUE TITLE
[Request] Notion Icon

### ISSUE THREAD

**Issue by raulcraveiro** [gusbemacbe/suru-plus#114]
I created a nativefier version of Notion (https://notion.so) and I would love to have a icon for it in the same style as Suru! <3

**Comment by gusbemacbe** [comment]
When I am ready with the Suru++ Ubuntu, I will be working with it.

**Comment by gusbemacbe** [comment]
Desculpe-me pela demora, eu estava muito ocupado com o repositório [Suru++ Ubuntu](https://github.com/Bonandry/suru-plus-ubuntu). Quando eu terminei o projeto dele, ia continuar neste projeto, mas a minha irmã e a amiga da minha amiga me perturbaram muito durante esta semana. 

Mas adicionado ícone finalmente. Está na versão `beta`.

**Comment by raulcraveiro** [comment]
Sem problemas! Eu adorei esse pacote de ícones, e já estou divulgando para o pessoal que conheço que utiliza Linux! hahaha

Inclusive acabei de dar uma olhada no ícone e ficou maravilhoso! ❤️
