### ISSUE TITLE
Can't make Thunar to use the folder color

### ISSUE THREAD

**Issue by BiglinuxLover** [gusbemacbe/suru-plus#115]
Hello, 
I've installed Suru++ for xfce and it's working well
I've also installed folder colors and chose manjaro color.
But it seems like thunar won't change folder color (see screenshot)
![Thunar](https://user-images.githubusercontent.com/38280629/55294847-a960c200-53fe-11e9-93ed-af29ea290eab.png)

**Comment by gusbemacbe** [comment]
Salut @BiglinuxLover !

Je vais regarder sur Suru++ Folder Colors.

**Comment by gusbemacbe** [comment]
Il est fixé. J'ai oublié d'inclure les couleurs sur d'autre fichier sur Suru++ Folder.

Pour changer la couleur des icônes monochromatiques, il faut que vous utilisez Suru++ Coloriser (seulement des dégradés) ou l'Oomox d'@actionless. Si vous ne voulez pas installer Oomox, vous devez utiliser des commandes sur le terminal : 

```
cd /Suru++/apps/16/
cd /Suru++/apps/symbolic/
cd /Suru++/mimetypes/16/
#etc ...
sed --in-place --follow-symlinks 's/#5c616c/#ta_couleur_favorite/g' *.svg
```

**Comment by BiglinuxLover** [comment]
désolé je n'ai pas capté 
je suis toujours en galère la dessus donc si vous pouvez m'aider ca serais super
quesque je fais la ?

**Comment by BiglinuxLover** [comment]
Finalement j'ai reussi a changer les couleurs
Merci en tout cas

**Comment by gusbemacbe** [comment]
<details>

Faites un clic sur un de ces sommaires-ci. 

<summary>Pour changer la couleur des icônes monochromatiques et des dossiers</summary>

1. Exécutez la command `yay -S oomox-git` dans le terminal (je pense que vous utilisez Manjaro Linux);
2. Ouvrez l'application Oomox.
3. Regardez le GIF :

<img src="https://raw.githubusercontent.com/gusbemacbe/suru-plus/beta/examples/Oomox%20%E2%80%93%20Example%202%20%E2%80%93%20Icons%20Colours.gif" alt="exemple 1" />

4. Choisissiez le chemin du dossier où vous voulez sauvegarder le thème d'icônes et et exportez le thème d'icônes :

<img src="https://raw.githubusercontent.com/gusbemacbe/suru-plus/beta/examples/Oomox%20%E2%80%93%20Example%206%20%E2%80%93%20Export%20icons.gif" alt="exemple 2" />

</details>

<details>

<summary>Pour changer la couleur des dossiers (Suru++ Folders ne change pas la couleur des icônes monochromatiques)</summary>

1. Ouvrez le terminal e exécutez la commande :

```
wget -qO- https://git.io/fhQdI | sh
```

Il est important de rappeler que le thème d'icônes Suru++ doit demeurer sur les dossiers `ton_prénom/.icons/` ou `ton_prénom/.local/share/icons` ou `/usr/share/icons`. Le thème d'icónes doit s'appele « Suru++ » ou « Suru++ 25 » ou « Suru++-25 » ou « suru-plus».

2. Pour changer la couleur désirée (par exemple, je choisis brown (brun)), exécutez la commande dans le terminal :

```
suru-plus-folders -C brown --theme Suru++
# ou
suru-plus-folders -C brown --theme Suru++\ 25
# ou
suru-plus-folders -C brown --theme Suru++-25
# ou
suru-plus-folders -C brown --theme suru-plus
```

Voici le résultat. 

</details>

<details>

<summary> Pour habiliter le dégrade des icônes monochromatiques (Suru++ Colourise ne change pas la couleur des dossiers)</summary>

1. Exécutez les commandes dans le terminal :

```
sudo wget https://git.io/fhbxw -O /usr/local/bin/suru-plus-colourise
sudo chmod a+x /usr/local/bin/suru-plus-colourise
```

2. Donc exécutez :

```
suru-plus-colourise
```

Vous receivez les questions, si vous peuvez choisir un des 9 dégrades.

Si vous n'aimez pas le dégrade, exécutez la même commande `suru-plus-colourise`. 

Mais si vous n'aimez pas aucun dégrade, vous peuvez utiliser Oomox et habiliter le dégrade e changer quelque deux couleurs du dégrade. 

</details>

**Comment by gusbemacbe** [comment]
OK, @BiglinuxLover ! De rien !
