### ISSUE TITLE
[Request]  super productivity icon

### ISSUE THREAD

**Issue by fla15** [gusbemacbe/suru-plus#116]
hi, could you add an icon for [super productivity](https://github.com/johannesjo/super-productivity) app?

**Comment by gusbemacbe** [comment]
Hi @fla15 !

When I am done with @Bonandry's [Suru++ Ubuntu](https://github.com/Bonandry/suru-plus-ubuntu), I will work on it.

**Comment by gusbemacbe** [comment]
Hello @fla15 !

It seems that it has already been added before. How did you install Super Productivity?

**Comment by fla15** [comment]
`sudo snap install superproductivity
`
on Ubuntu 19.04
![Screenshot from 2019-08-20 17-54-05](https://user-images.githubusercontent.com/30726939/63350931-4da2c100-c32c-11e9-8105-c9cf0b630fe0.png)
