### ISSUE TITLE
Comment changer les icons de programme comme Inkscape

### ISSUE THREAD

**Issue by BiglinuxLover** [gusbemacbe/suru-plus#117]
Bonjour, désolé de vous deranger mais j'aimerais savoir comment changer les icons de programmes tel que Inkscape.
J'aime beaucoup les icons Suru++ mais j'aimerais avoir des icons comme ceci:
![Inkscape icons numix ](https://user-images.githubusercontent.com/38280629/55482456-7a279c00-561c-11e9-9e0f-1376cdec6a2d.png)
Plutot que ceci:
![Inkscape icons Suru](https://user-images.githubusercontent.com/38280629/55482475-84499a80-561c-11e9-9efd-e847db9518ec.png)
Ca serais dommage qu'on ne peut pas changer ces icons 
Merci en avance
Sinceremment 
Ahmed

**Comment by gusbemacbe** [comment]
@BiglinuxLover 

Si vous voulez que Inkscape utilise les icônes de Suru++ ou d'autre thème d'icônes individuellement, et indépendamment du système, je vous recommande à utiliser la version alpha d'Inkscape – 1.0.1 Alpha. Vous devez compiler, en utilisant la commande `yay -S inkscape-git` sur le terminal ou télécharger l'AppImage d'Inkscape. 

Si vous voulez demeurer avec la version 0.92, je n'ai encore pas créé le paquet d'icônes au style de Suru, donc vous devez utiliser un paquet d'icônes d'Inkscape que vous pouvez trouver sur OpenDesktop:

1. https://www.opendesktop.org/p/1168331/
2. https://www.opendesktop.org/p/1168718/

Extrayez, renommez un fichier SVG pour `icons.svg` et mettez-le sur `~/.config/inkscape/icons/`.

**Comment by BiglinuxLover** [comment]
@gusbemacbe 
Je comrends mais je ne suis pas sous Manjaro linux 
Donc  `yay -S inkscape-git` ne fonctionera pas.
Mais j'aimerais bien utiliser le packet d'icones numix icon theme pour Inkscape,Gimp et d'autres application 
Comment je fais ca.
Merci beaucoup pour votre réaction

**Comment by gusbemacbe** [comment]
Quel est vôtre distribution de Linux, @BiglinuxLover ?

**Comment by BiglinuxLover** [comment]
@gusbemacbe 
Je suis sous Linux mint 19 Xfce

**Comment by gusbemacbe** [comment]
Il n'y a pas un PPA de *nightly builds* d'Inkscape, donc vous devez télécharger la version alpha de l'AppImage d'Inkscape, [cliquez ici](https://inkscape.org/release/inkscape-1.0alpha0/gnulinux/appimage/dl/) directement du site d'Inkscape.

1. Exécutez la commande sur le terminal :

```
chmod a+x ./Inkscape-9dee831-x86_64.AppImage
```
2. Ouvrez l'Inkscape e donc fermez-le.
3. Installez le thème d'icônes Numix sur le `~/.icons/`.
4. Ouvrez e voyez, et cliquez Sur Édition > Préférences : 

![image](https://user-images.githubusercontent.com/2257024/55487422-712ad080-5604-11e9-9384-63aab74113c0.png)

Si vous demeurez avec la version 0.92, vous devez demander aux développeurs @palob et @Foggalong de séparer le paquet d'icônes pour Inkscape du thème d'icônes Numix.

**Comment by BiglinuxLover** [comment]
Merci beaucoup just un petit sousi: je veux utiliser le theme blanc mais ca ne veut pas changer 
des idées ?
![Inkscape dark interface ](https://user-images.githubusercontent.com/38280629/55488591-3d61a200-5628-11e9-963e-2f0dd8b82e0f.png)

**Comment by BiglinuxLover** [comment]
et puis j'ai peut-etre trouvé le ppa nightly pour Inkscape
voila le lien: https://launchpad.net/~inkscape-nightly/+archive/ubuntu/ppa

**Comment by gusbemacbe** [comment]
Il faut que vous utilisez le thème sombre d'icônes du Numix Project. Regardez le Numix Dark.

**Comment by gusbemacbe** [comment]
> et puis j'ai peut-etre trouvé le ppa nightly pour Inkscape
voila le lien: https://launchpad.net/~inkscape-nightly/+archive/ubuntu/ppa

Sur ce PPA-ci, il n'y a pas de la version 1.0.1. Peut-être https://launchpad.net/~inkscape.dev/+archive/ubuntu/trunk.

**Comment by BiglinuxLover** [comment]
Enfait je veux garder le theme Suru++ sur mon ordinateur 
mais pour  les icons de Inkscape et Gimp je voudrais qu'ils utilisent les icons numix.
Et quand j'utilise le build nightly le thème GTK et noir 
Ya t-il un moyen pour changer le theme gtk?
Merci infiniment pour votre aide

**Comment by BiglinuxLover** [comment]
Après l'installation du trunk build tout est parfait 
Merci cher monsieur de m'avoir aidé 
Je vous remercie fortement.

**Comment by gusbemacbe** [comment]
> Ya t-il un moyen pour changer le theme gtk?

Impossible dans la version 0.92. Seulement dans la version 1.0.1 Alpha d'Inkscape. Pour utiliser le thème d'icônes Numix pour Inkscape 1.0.1 e Suru++ pour l'ordinateur, il fault crér le paquet d'icônes Numix pour Inkscape. 

Vous pouvez voir comme changer du thème GTK d'Inkscape :

![INkscape](https://user-images.githubusercontent.com/2257024/55489677-c4068700-5608-11e9-8c00-05bdf877393f.gif)

**Comment by gusbemacbe** [comment]
Je viens juste de publier la suggestion sur leur repositoire Numix : https://github.com/numixproject/numix-core/issues/4837

**Comment by gusbemacbe** [comment]
@BiglinuxLover 

J'ai découvert un truc. :-) 

Donc tu peux utiliser Suru++ dans le système pendant que tu peux utiliser Numix dans l’Inkscape.

1. Allez au dossier `~/.config/inkscape/`;
2. Ouvrez le fichier `preferences.xml` avec l'éditeur de texte;
3. Cherchez « `iconTheme="Suru++"` » et remplacez « `iconTheme="Suru++"` » pour « `iconTheme="Numix"` ». Sauvegarde-le.
