### ISSUE TITLE
[Request] RMLint Icon

### ISSUE THREAD

**Issue by pwd-github** [gusbemacbe/suru-plus#118]
It would be marvellous if this icon could be provided too.

**Comment by gusbemacbe** [comment]
Hello @pwd-github !

When I am done with @Bonandry's [Suru++ Ubuntu](https://github.com/Bonandry/suru-plus-ubuntu), I will work on it.

**Comment by pwd-github** [comment]
Thank you @gusbemacbe

**Comment by gusbemacbe** [comment]
Added icon and ready. It is in the branch `beta`.

**Comment by pwd-github** [comment]
Thank you @gusbemacbe, you're awesome!
