### ISSUE TITLE
[Request] audio-card-usb-symbolic icon

### ISSUE THREAD

**Issue by Prototik** [gusbemacbe/suru-plus#120]
With Gnome 3.32 gnome-control-center adopted new design for some sections, especially for sound category.

The problem is with new design each audio device got own icon, but Suru (actually Adwaita/hicolor too) has missing icon for audio-card-usb-symbolic type, which causes fallback "unknown type" icon for my headset.

<details>
  <summary>Missing icon</summary>
  <img src="https://user-images.githubusercontent.com/1416030/55867053-40e9b180-5b71-11e9-8b8e-ade52cfcb4f3.png">
</details>

My temp workaround just create a dumb symlink for existing icon:
```bash
mkdir -p ~/.local/share/icons/hicolor/scalable/devices/
ln -s /usr/share/icons/Adwaita/scalable/devices/drive-harddisk-usb-symbolic.svg ~/.local/share/icons/hicolor/scalable/devices/audio-card-usb-symbolic.svg
```

<details>
  <summary>Hotfix ¯\_(ツ)_/¯</summary>
  <img src="https://user-images.githubusercontent.com/1416030/55867335-d38a5080-5b71-11e9-97f8-80c2fc29872a.png">
</details>

It would be nice if Suru will ship this icon out-of-box.

**Comment by gusbemacbe** [comment]
Привет Сергей!

Когда я с репозиторием [Suru++ Ubuntu](https://github.com/Bonandry/suru-plus-ubuntu) готовый, я добавлю зта икона сегодня ночью. 

Спасибо за рапорт, Сергей!

(Извините за мои русские ошибки, я изучаю Руссикй.)

**Comment by gusbemacbe** [comment]
Извините, @Prototik, я был в сильной спешке я не мог добавить недостающую иконку в репозиторий в ту ночь потому что моя сестра и глупый приятель беспокоили очень меня. 

Но добавля́емая икона. :-)
