### ISSUE TITLE
To preserve "inkscape:label" and "id" in the script ffsvg and to exclude certain icons

### ISSUE THREAD

**Issue by gusbemacbe** [gusbemacbe/suru-plus#121]
Hello @SmartFinn !

1. Is it possible to preserve the `inkscape:label`s and `id`s during the script `ffsvg`?
2. Is it possible to exclude some icons (`firefox.svg`, etc.) during the script `ffsvg` which will optimise all once in a while?

**Comment by SmartFinn** [comment]
> Is it possible to preserve the inkscape:labels and ids during the script ffsvg?

Comment the following lines in [_svgo.yml](https://github.com/gusbemacbe/suru-plus/blob/master/scripts/_svgo.yml)

```
  # removes editors namespaces, elements and attributes
  # - removeEditorsNSData
```

```
  # removes unused IDs
  # - cleanupIDs:
  #    minify: false
  #    preserve: [ 'current-color-scheme' ]
```

But after the changes SVG files will be huge.

> Is it possible to exclude some icons (firefox.svg, etc.) during the script ffsvg which will optimise all once in a while?

It's not provided.

**Comment by gusbemacbe** [comment]
> Comment the following lines in [_svgo.yml](https://github.com/gusbemacbe/suru-plus/blob/master/scripts/_svgo.yml)
> 
> ```
>   # removes editors namespaces, elements and attributes
>   # - removeEditorsNSData
> ```

Unfortunately it left many Inkscape tags. I pulled a suggestion in the issues list of the SVGO repository.
