### ISSUE TITLE
[Request] Feedly and Pocket Casts icon

### ISSUE THREAD

**Issue by raulcraveiro** [gusbemacbe/suru-plus#122]
Hello! Making another request 😬

I use Pocket Casts (via snap) and Feedly (via nativefier) and would love to see some native icons for them as well.

Thank you guys for the amazing work! ❤️

**Comment by gusbemacbe** [comment]
Olá @raulcraveiro !

O ícone de Pocket Casts já foi adicionado antes. [Visualize pocket-casts.svg](https://github.com/gusbemacbe/suru-plus/blob/beta/Suru++/apps/64/pocket-casts.svg).

Como você instalou esta aplicação via Snap, o ícone dela é predefinido ou codificado fixamente (veja [codifcação rígida na Wikipédia](https://pt.wikipedia.org/wiki/Codifica%C3%A7%C3%A3o_r%C3%ADgida)) e os arquivos .`desktop` não estão hospedados na pasta `~/.local/share/applications` ou `/usr/share/applications`, por favor, segue o pequeno tutorial [Snap-built apps](https://github.com/gusbemacbe/suru-plus/tree/beta#snap-built-apps) neste repositório.

**Comment by raulcraveiro** [comment]
Eu estava alterando os ícones através do Menulibre, mas ele não encontra nem pesquisando por pocket, nem por casts, nem por pocket-casts. Acabei de tentar procurar manualmente na pasta, mas também não encontrei.

Eu instalei através do "HOME directory for GTK", isso pode ter alguma relação?

**Comment by gusbemacbe** [comment]
Você precisa usar `update-desktop-database` no terminal.

O arquivo Snap onde hospeda os arquivos .`desktop`, é inacessível, seu usuårio é root e Menulibre não consegue modificar manualmente os arquivos `.desktop` sem executar como root.

**Comment by raulcraveiro** [comment]
Não entendi, como faço isso?

Eu tava vendo aqui, e o comando baixou os ícones do branch "master", mas parece que o ícone do Pocket Casts está apenas no branch "beta".

**Comment by gusbemacbe** [comment]
@raulcraveiro 

Só adicione `TAG=beta` antes do `sh`, por exemplo:

```
wget -qO- https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/install.sh | TAG=beta sh
```

Atualizarei o README ou adicionarei à wiki, como instalar e atualizar as *nightly builds* do tema de ícones.

**Comment by raulcraveiro** [comment]
Muito obrigado pela ajuda e paciência! Eu ainda sou novato no mundo Linux, então estou aprendendo aos poucos. 

Agora com o beta apareceu o ícone do pocket casts e do Notion. ❤️

**Comment by gusbemacbe** [comment]
Adicionado ícone de Feedly.

Observe que na versão `beta`, mudei de `64` para `scalable` para tornar [Suru++ Folders] universal com ambos os Suru++ 25, [Suru++ Ubuntu](https://github.com/Bonandry/suru-plus-ubuntu) e com [GNOME++](https://github.com/Bonandry/gnome-plus).

**Comment by gusbemacbe** [comment]
@raulcraveiro 

A[c]tualizei a wiki. Eu traduzi a wiki em português brasileiro e em português europeu para facilitar a compreensão dos usuários/utilizadores novatos ou não-novatos de Linux.  Pode[s] visitar a wiki dire[c]tamente: [Suru++ 25 Wiki](https://github.com/gusbemacbe/suru-plus/wiki)

**Comment by gusbemacbe** [comment]
@raulcraveiro 

Acabei de lançar a nova versão oficial com centenas de novas funções. Dê uma olhada no README (já está em português) e na CHANGELOG (no repositório e não na lista de lançamentos). 

Se puder, por favor, gostaria que você e os teus amigos votassem meu produto diretamente: https://www.opendesktop.org/p/1238162/

**Comment by raulcraveiro** [comment]
Vou dar uma olhada no readme e no changelog agora. Já deixei um voto lá no OpenDesktop, esse projeto merece muito :)
