### ISSUE TITLE
[Request] add ".cbz"  mime-type icon

### ISSUE THREAD

**Issue by demoy** [gusbemacbe/suru-plus#123]
.cbz is the extension use to indicate a comic book, it just a zip archive containing images (https://en.wikipedia.org/wiki/Comic_book_archive). It's recognize by common document viewers (evince, okular, calibre, etc).. for some inspiration papirus uses a yellow icon with the batman logo for .cbz

![](https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-calibre-theme/master/resources/images/mimetypes/cbr.png)

Here are the paths specific file names used by papirus:

application-vnd.comicbook+zip.svg (actual file, all the rest below sym link to it)
application-x-cbz.svg
application-x-cbr.svg
application-x-cb7.svg
application-x-cbt.svg
application-x-cba.svg

**Comment by gusbemacbe** [comment]
Hi @demoy 

Tonight I will add it to the `beta` branch, after finishing the translations in the Suru++ 25's `wiki` (at the top of this repository page).

**Comment by gusbemacbe** [comment]
Hi @demoy 

I have finished the job, but I need to add the missed icons to 16px folder.

I have just added `.cbz` files and its symllinks. Not just a Batman file, you also can choose of the alternatives you prefer the most. :-) See the screenshot:

![image](https://user-images.githubusercontent.com/2257024/56570750-e1889a00-6591-11e9-8a5f-9c4af7dc74cb.png)

If you want to change the alternative icon, please visit the wiki and choose "Changint the alternative icon".

**Comment by demoy** [comment]
The W looks really cool.. is that an original concept?

**Comment by gusbemacbe** [comment]
No, It was based on the 2016 film Wonder Woman. If you want an original Wonder Woman insignia, I must add more.

**Comment by demoy** [comment]
No I'm fine. Thanks for the offer
