### ISSUE TITLE
Transmission-qt icon doesn't inherit KDE colorscheme in panel

### ISSUE THREAD

**Issue by demoy** [gusbemacbe/suru-plus#124]
![Screenshot_20190422_173732-1](https://user-images.githubusercontent.com/2396524/56537285-c97b3100-6525-11e9-88a9-d0ac2f805561.png)
the icon show in panel above

![Screenshot_20190422_174230](https://user-images.githubusercontent.com/2396524/56537448-3262a900-6526-11e9-95f9-4fcbaa3f43d0.png)
the icon shown in menu (same plasma theme)

**Comment by gusbemacbe** [comment]
Fixed, but it is in the branch `beta`.

**Comment by demoy** [comment]
I checkout the beta, the fixed didn't work. Taking in a look at "transmission-qt.svg" I noticed it points to "torrent.svg". The menu icon uses "transmission.svg" (so it works). Transmission-gtk also points to torrent.svg (meanwhile transmission-remote-gtk.svg links to transmission.svg), maybe have them link to transmission.svg. And/or fix the colorscheme in torrent.svg.

I love the mime changes on the beta branch. I noticed few state the mime extension on the icons while the majority don't.. I liked the omission more

**Comment by gusbemacbe** [comment]
@demoy 

I will investigate all symlinks and both torrent and transmission.

>  I noticed few state the mime extension on the icons while the majority don't.. I liked the omission more

Yes, I am still redesigning. I was going to add Comic Book icons, but as the mimetypes icons were too classic, old and traditional Suru, so I wanted to make less Suru and more cyberpunk, futuristic, modern, scifi and Papirus-like. I have promised to somebody that I was going to redesign the mimetypes icons.

I also added the exclusive and special folders, in tribute to the month of astronomy and scifi and also alternatives `.theme` mimetypes icons that you can choose the most you prefer.

Three exclusive and special folders are:
* Tribute to the Black Hole, with nternational Day of Astronaut, Cosmologist and Astonomy
* Star Trek
* Star Wars 
* Avengers 4

And the alternatives `.theme` icons:
* Four Star Trek suits
* Obi Wan Kenobi's suit
* Darth Vader's suit

Soon I will add more alternatives with suits of main Star Wars suits (Ren, Luke Skywalker, Anakin Skywalker) and Terran Empire suit. 

I also finished the wiki, translating in 7 languages. 

Suru++ won a new @Roboron3042's Cyberpunk Neon gradient for 16px icons and also won new folders with colours of Cyberpunk Neon and of Disco Ringo.

**Comment by gusbemacbe** [comment]
@demoy 

I have just released officially. See if it is fixed and you catch comics icons.

**Comment by demoy** [comment]
Yes it did thank you
