### ISSUE TITLE
Mimetypes icons alternatives

### ISSUE THREAD

**Issue by lapega** [gusbemacbe/suru-plus#129]
The new version of Suru++ (Barcelona) has changed a lot the mimetypes icons, and some of them looks old.  
![Captura de pantalla de 2019-05-22 09-16-48](https://user-images.githubusercontent.com/572502/58173670-5672f080-7c72-11e9-9700-87ad31b3bce6.png)

Is there an option to change this icon to an alternative version?

Thank you!

**Comment by gusbemacbe** [comment]
Hi @lapega,

I am a bit confused. Which one of them is old?

Only if you use KDE, you can modify the mimetype icon. There is an app called MIME Editor.

**Comment by lapega** [comment]
Sorry for the little explanation.
I'm talking about the new mimetypes icons, (.txt, .doc, .sh, etc.).
The old ones (version 25 and previous) looks more integrated than the new ones.

I'm attaching a screenshot of Suru++ Barcelona and Suru++ Ubuntu. You can spot the differences in .txt files:

![Captura de pantalla de 2019-05-22 16-22-55](https://user-images.githubusercontent.com/572502/58202538-395c1300-7cae-11e9-973a-70c659b39ea9.png)
![Captura de pantalla de 2019-05-22 16-24-01](https://user-images.githubusercontent.com/572502/58202539-395c1300-7cae-11e9-8af1-dc2cb71523bf.png)

**Comment by gusbemacbe** [comment]
Hola @lapega !

Estoy viendo que eres hispanohablante, voy a explicar en español.

Mi objetivo de ese tema es hacer Suru++ más cybperunk, futurista y menos Suru. Puedes hacer _downgrade_, utilizando el tag [v25.3](https://github.com/gusbemacbe/suru-plus/tree/v25.3), ejecutando en el terminal:

```
wget -qO- https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/install.sh | TAG=v25.3 sh
```

Se te gustaría mantener la última versión del tema de iconos, y quieres utilizar los iconos viejos de tipo de archivos, descarga dos temas – `master` y `v25.3`, entonces copia la caprpeta `64` de la versión `v25.3` para la carpeta `scalable` de la versión `master`. 

Reconsiderando tu sugerencia, crearé tres alternativas - vieja, con extensión o sin extensión.

**Comment by lapega** [comment]
Gus, que buena respuesta.
Con la línea de comandos que me recomiendas ya estoy feliz, y si además generas esas alternativas, mucho mejor!

Mil gracias!!!
