### ISSUE TITLE
LyX Icon

### ISSUE THREAD

**Issue by dmiranda2** [gusbemacbe/suru-plus#15]
It would be great if you could add an icon for Lyx.

* Distribution and version:
Arch 
* Distribution environment:
- Gnome
- KDE
- Budgie

[Desktop Entry]
Type=Application
Name=LyX
GenericName=Document Processor
Comment=High level LaTeX frontend
Keywords=WYSIWYG;WYSIWYM;TeX;LaTeX;GUI;frontend;editor;
Icon=lyx

Site: https://www.lyx.org/

**Comment by gusbemacbe** [comment]
I will update only the next Thursday

**Comment by gusbemacbe** [comment]
Added LyX icon, rin reference to #https://github.com/gusbemacbe/suru-plus/commit/49c8974df00e46df22de9274e25313d695848641.

Closing the issue.
