### ISSUE TITLE
GSconnect icon needed

### ISSUE THREAD

**Issue by Kandelai** [gusbemacbe/suru-plus#18]
A popular extension GSconnect in the gnome extensions creates an icon in the media menu and top bar that is not part of your icon theme, and so it stands out, glaringly. Can you include an icon for it in your theme?

**Comment by gusbemacbe** [comment]
Hello @Kandelai 

The icon is already present before. Check: https://github.com/gusbemacbe/suru-plus/blob/master/apps/scalable/gsconnect.svg

But if the icon does not display well the app, it must be because your ap has a different icon name. You need to go to '/usr/share/applications' and open a desktop file of GSConnect and find `Icon=...` and copy and paste the icon name here.

**Comment by Kandelai** [comment]
Hi there, it does display the icon you have shown in blue, but that is the issue. In the top bar (I am using a dark theme) all your other icons are displayed in white except the GSConnect which is blue like your link. Does that make sense?

I will attach a screenshot.
![gsconnecticon](https://user-images.githubusercontent.com/39681298/41319207-e57b00d8-6e4f-11e8-80e8-9fc86184e463.png)

**Comment by gusbemacbe** [comment]
Strange, it appears on Andrea's computer:

![image](https://user-images.githubusercontent.com/2257024/41319695-1fc618f4-6e73-11e8-8727-0c1a8f1edd86.png)

I am confused. Does it affect in both Suru++ and Suru++ Dark?

**Comment by Kandelai** [comment]
Yes, it happens in both. Here is what I see;
![menu_003a](https://user-images.githubusercontent.com/39681298/41328207-bb749d4a-6e7b-11e8-9990-c87dd71284b0.png)

**Comment by Magog64** [comment]
Hi Kandelai, go to the APPS / SCALABLE folder, search for and delete the gsconnect icon, restart the PC and check if it works

**Comment by gusbemacbe** [comment]
@Kandelai 

I have just released the new version. I and @Magog64 have fixed this. See if it works for you.
