### ISSUE TITLE
MIssed Icon's

### ISSUE THREAD

**Issue by sutterkaine75** [gusbemacbe/suru-plus#20]
* **Distribution and version:**
* **Distribution environment:**
  - [ ] Cinammon
  - [x ] Gnome
  - [ ] KDE
  - [ ] LXDE
  - [ ] MATE
  - [ ] XCFE
  - [ ] Other. Name here: 

| App name | App type                           | Icon name | Description    | Reference            |
| ------------- |-----------------------------      | ---------      | -------------- | -------------------- |
| Psensor | Debian                                 | Psensor    | Cpu temperature | https://wpitchoune.net/psensor/ |
| Songwrite     | Debian                            | Songwrite       | Make Guitar CRD          | http://www.lesfleursdunormal.fr/static/informatique/songwrite/index_en.html                  | SweetHome3d  

* **Screenshots**

* **Additional information:**

**Comment by sutterkaine75** [comment]
OK! Tnx!!.. I requested other icon's..mame and now I dont' remenber very well!
So i dont' get never them...Tnx!

**Comment by gusbemacbe** [comment]
Hi @sutterkaine75!

The MAME icon is present in this icons theme. But if your MAME app is Flatpak-built, Snap-built, etc., you need to go to `/usr/share/applications` and open the file MAME with text editor and find the `Icon=`. Copy the whole icon name and paste it here.

**Comment by gusbemacbe** [comment]
Can I know your distribution and graphic environment (for example, GNOME, KDE, etc.)? And where are you from?

**Comment by sutterkaine75** [comment]
Ubuntu 18.04 with gnome of course. The best desktop in the world..;D.
I live in ANCONA-IT

**Comment by gusbemacbe** [comment]
Ciao @sutterkaine75 

Poi io parlo italiano.

Come stai utilizzando Ubuntu 18.04, ti raccomando il [Suru++ only for Ubuntu](https://github.com/Magog64/suru-plus/) di @Magog64 (lui anche è italiano), progettato ed ottimizzato per le distribuzioni Ubuntu cl GNOME.

Come stai utilizzando solamente l'Ubuntu, il mio repositorio di tema di icone non è necessario, salvo che tu voglia utilizzare il mio tema di icone nelle altre distribuzioni non-Ubuntu e negli altri ambiente di interfacce grafica non-GNOME.

**Comment by gusbemacbe** [comment]
> I saw it...Icon's in the PPA is ok so in the snap there isn't.

Perciò, devi copiare il file di impostazione di desktop dell'applicazione Mame dalla cartella `/var/lib/snapd/desktop` per la cartella `tuo_nome/.local/share/applications`. Io ho fornito i file desktop ([eccoli](https://github.com/gusbemacbe/suru-plus/tree/master/desktop), ma Mame non è in questa lista. Devo scaricare ed installare l' applicazione Mame via Snap.

**Comment by gusbemacbe** [comment]
Se tu hai altre distribuzioni, devi aspettare ch'io vado finalizzare la versione alfa di Suru++ Completo, eliminando tutti i bug. Quando lei sarà finalizzata, io ti chiamerò.

**Comment by sutterkaine75** [comment]
ottimo ! Garzie mille!

**Comment by gusbemacbe** [comment]
Ciao @sutterkaine75 !

Le icone di Songwrite e Psensor sono aggiunte alla nuova versione di Suru++ Alfa. La nuova versione si fonderà in questa versione vecchia e rilasciata domani. Sii pronto per la nuova versione domani.

**Comment by sutterkaine75** [comment]
GRandeeeeee!!!!! :D... Prontissimo!!!

**Comment by gusbemacbe** [comment]
Adesso ufficialmente rilasciata la nuova versione inclusa con queste icone.

**Comment by sutterkaine75** [comment]
Stupendaaaaa!!!!!! che figataaaaaAAAAAAAAaaaaa!!!!!..senti songwriter non mi funziona.. come posso fare.. grazie mille!! Questo icon set è MICIDIALEEEE!!!LOVE!

**Comment by gusbemacbe** [comment]
Ciao @sutterkaine75 !

1. Apri il terminale e scrivi:
    ```
     $ sudo chmod -R 777 /usr/share/applications
    ```
2. Apri il tuo Dolphin o Nautilus o Nemo o Thunar, vai alla cartella `/usr/share/applications`.
3. Vai all'applicazione Songwrite ed aprila col editore di testo (come Gedit).
4. Trova `Icon=songwrite3.png` e cambia per `Icon=songwrite3`. Salvala. 

Gli sviluppatori di alcune certe applicazioni utilizzano il cammino assoluto e l'estensione, impedendo la nuova icona di tema di icone di essere applicata all'applicazione. Perciò, devi andare a quella cartella di applicazioni ed editare i file di configurazione di desktop.

**Comment by sutterkaine75** [comment]
Grazie mille della risposta...

[Desktop Entry]
Name=Songwrite
GenericName=Tablature editor
Type=Application
Categories=Application;AudioVideo;Audio;Music;AudioVideoEditing;Player;
Terminal=false
Exec=songwrite
Comment=guitar tablature editor and player
Icon=/usr/share/songwrite/data/songwrite_32x32.png

dentro c'e' questo... non vedo testo simile a  quello che tu mi dici.

**Comment by sutterkaine75** [comment]
Perfetta!!! Anche questa!!! Stupendo! Per me è l Icon set definitivo! Grazie mille....

Se ho altre richieste posterò qua!!!

**Comment by gusbemacbe** [comment]
Ok, apri il nuovo issue, perché questo issue è chiuso per essere risolto.
