### ISSUE TITLE
No icons for Zeals

### ISSUE THREAD

**Issue by razouck** [gusbemacbe/suru-plus#21]
There are no icons for Zeal.

**Comment by gusbemacbe** [comment]
HI @razouck 

Are you referring to https://zealdocs.org/?

If so, I will add it to [Suru++ Alpha version 7](https://github/com/gusbemacbe/suru-plus-alpha) and merge it into this repository when the beta version will be released.

**Comment by gusbemacbe** [comment]
Hi @razouck,

The Zeal icon is added to the new version of [Suru++ Alpha](https://github.com/gusbemacbe/suru-plus-alpha). Tomorrow it will be released and merged into this repository.

**Comment by gusbemacbe** [comment]
The new version included with the icon Zeals is officially released.
