### ISSUE TITLE
Credits and licences

### ISSUE THREAD

**Issue by gusbemacbe** [gusbemacbe/suru-plus#24]
Hello @varlesh and @Foggalong and @palob!

I credited you because my redesigned folder icons are based on Papirus places icons and my redesigned icons are based on Numix icons. 

I would like to know if [AUTHORS](https://github.com/gusbemacbe/suru-plus/blob/master/AUTHORS), [COPYING](https://github.com/gusbemacbe/suru-plus/blob/master/COPYING) and the licences in the README end are correct. 

If something is incorrect, please correct and suggest me only if you have time. 

Thank you for your attentions, understandings and patience!

**Comment by varlesh** [comment]
Ok :+1:

**Comment by Foggalong** [comment]
It's all goo with regards to Numix work :+1:

**Comment by gusbemacbe** [comment]
Ok, thank you for your answers!

**Comment by palob** [comment]
Thanks for the laurels :-)
