### ISSUE TITLE
Misleading README file

### ISSUE THREAD

**Issue by darksonic6** [gusbemacbe/suru-plus#27]
The readme file says this repo includes a script to change the colors of the folder icons, even though there is none.

**Comment by gusbemacbe** [comment]
Hi @darksonic6 

ARe you referring to [Suru++ Folders' README.md](https://github.com/gusbemacbe/suru-plus-folders) or this README here?

**Comment by gusbemacbe** [comment]
Ready. I have updated README. Better now?
