### ISSUE TITLE
[Request] Google Play Music Desktop Player icon

### ISSUE THREAD

**Issue by fishears** [gusbemacbe/suru-plus#28]
icon=com.googleplaymusicdesktopplayer.GPMDP

app url https://www.googleplaymusicdesktopplayer.com/

Please consider making a Suru icon for this application

Thank you

**Comment by gusbemacbe** [comment]
Hi, tomorrow I will add this icon.

**Comment by fishears** [comment]
thank you

**Comment by gusbemacbe** [comment]
Sorry for the late. I have already added the icon, but to the beta branch, so I had to correct other icons, add new icons and test new folders. I have just released the new official version. 

It is added.

**Comment by fishears** [comment]
it's perfect. thank you
