### ISSUE TITLE
Zotero Icon

### ISSUE THREAD

**Issue by jcuenod** [gusbemacbe/suru-plus#37]
Could you add an icon for Zotero. Zotero is note taking and bibliographic management software (common in academic fields):

<img src="https://www.zotero.org/support/_media/logo/zotero_256x256x32.png" />

The branding page may be of interest: https://www.zotero.org/support/brand

```
[Desktop Entry]
Type=Application
Name=Zotero
Icon=zotero
Categories=Office
```

**Note:** I am actually using `suru-plus-telinkrin` so I would really like to see it make it into that package. Thanks for the great icon theme!

**Comment by gusbemacbe** [comment]
I added it to the task in the Project. 

As for Suru++ Telinkrin, when Suru++ will be free of rendering bugs, I will Suru++ into Suru++ Telinkrin, because Suru++ Telinkrin is still version 14 and this Suru++ is version 20.

**Comment by jcuenod** [comment]
Okay, I've actually mocked one up... I'll submit a PR and you can do with it as you see fit :)

**Comment by jcuenod** [comment]
Thanks :+1:
