### ISSUE TITLE
Icon for VMWare Horizon Client

### ISSUE THREAD

**Issue by bridnour** [gusbemacbe/suru-plus#41]
Is it possible to make a suru++ version of the "VMWare Horizon Client" Icon.

This is it's .desktop entry:
[Desktop Entry]
Encoding=UTF-8
Type=Application
Icon=vmware-view.png
Exec=vmware-view %u
MimeType=x-scheme-handler/vmware-view
Categories=Application;Network;
Name=VMware Horizon Client

This is the default icon:
![vmware-view](https://user-images.githubusercontent.com/33814396/46380439-428d6680-c670-11e8-8deb-dbfda90971aa.png)

**Comment by gusbemacbe** [comment]
Hi @bridnour !

It is hard-coded because of extension `.png`. You need to remove `.png`. 

It is added to the tasks at the Project. I will add this icon to the unstable branch.

**Comment by bridnour** [comment]
Thanks!

I'll be sure to remove the .png in the desktop entry.

**Comment by SmartFinn** [comment]
@gusbemacbe a small note, these file extension png, svg, and xpm do not make icon hardcoded. Icon lookup function removes the extensions wherever I tested it. Do you know a framework/distro where is not worked?

**Comment by gusbemacbe** [comment]
@SmartFinn 

In Deepin OS and in Manjaro. 

In my Manjaro now, I have just tested the desktop files, adding the extension, strange, it works. I do not understand. Before, one of desktop files had that extension and it did not appear having an correct icon applied by the icons theme. Maybe it must be Deepin OS. I stopped using Deepin OS some months ago due to the bug of keyboard.

**Comment by gusbemacbe** [comment]
Under Manjaro, I have applied your icons theme Papirus, tested another time, it still works. 

It must be Deepin OS. But if I remember correctly, some Flatpak-built and snap-built apps used the extension and did not appear having correct icon applied by the icons theme. 

I have LIbreOffice and other installed via flatpak now and let me test, using your icons theme.

**Comment by SmartFinn** [comment]
@gusbemacbe in Deepin 15.6 it works too.

After added `.png` to `Icon` value, the icon applied:

![image](https://user-images.githubusercontent.com/819186/46394377-9db36d80-c6f1-11e8-9203-6b9854b5736f.png)

**Comment by gusbemacbe** [comment]
Then it means it can be because of Gravit metadata with base64 which prevents the icon of being applied or because I had multiple environments in the same desktop.

**Comment by gusbemacbe** [comment]
Hi @bridnour!

The icon has been added to the [unstable branch](/gusbemacbe/suru-plus/tree/unstable). It will be merged into the master branch tomorrow.
