### ISSUE TITLE
Icon requests: Natron and Etcher

### ISSUE THREAD

**Issue by MaCroX95** [gusbemacbe/suru-plus#42]
Please add icons for Natron, the open-source video compositing software that is availible on 
Original icon:
![image](https://user-images.githubusercontent.com/21268648/46489135-e871da00-c804-11e8-87db-89c761a03326.png)
and Etcher, the open-soruce bootable USB flash drive creating tool
Original icon:
![image](https://user-images.githubusercontent.com/21268648/46489198-0fc8a700-c805-11e8-9f12-ecc0f0782d72.png)

Awesome project, keep up the good work and thank you!

**Comment by gusbemacbe** [comment]
Hello @MaCroX95!

All the icons have been added to the [unstable branch](/gusbemacbe/suru-plus/tree/unstable). It will be merged into the master branch tomorrow.
