### ISSUE TITLE
Authorisation to copy the icons of actions and status of Papirus

### ISSUE THREAD

**Issue by gusbemacbe** [gusbemacbe/suru-plus#45]
Hi @varlesh and @SmartFinn!

I would like to ask for your authorisation to copy the icons of actions and status of Papirus to replace the grey monochromatic icons for same reasons:
1. The original author did not build correctly the icons theme, actions and status are messed and mixed. Some folders are unnecessary. I found Numix and Papirus very efficient. 
2. I will replace the monochromatic icons of actions and status for colourful icons of actions and status of Papirus, but I will readjust and modify some icons, as principally Insync icons to keep Suru++ icons original. 
3. Suru++ 20 needs to be totally different of Suru++ Ubuntu. Suru++ 20 is very macOS-like and symbolises the elegance, the cyberpunkness, the futurism, the vividness (based on new macOS and iOS icons colours) and the modernity, while Suru++ Ubuntu is conservative, desaturated, traditional and very Ubuntu-like. Therefore, Suru++ 20 fits very well with Papirus icons of actions and status.
4. Suru++ 20 fits very well more with `#5C616C` (colour of Papirus small icons of actions and status) than with ` #808080` because `#5C616C` is an elegant colour. With this new colour, Suru++ 20 will fit perfectly with Adapta. 

Thank you for your attention and understanding!

**Comment by AGitBoy** [comment]
Hi, I'm not the owner of the Papirus theme, but I know that Papirus is licensed under the GPLv3, and so is Suru++, as long as you fulfill the needs outlined in the GPLv3, you should be fine to copy it.

**Comment by SmartFinn** [comment]
@gusbemacbe yes, @AGitBoy is right, not need to ask the authorization when you using under the same license.
