### ISSUE TITLE
Icons for other Jetbrains IDEs

### ISSUE THREAD

**Issue by AGitBoy** [gusbemacbe/suru-plus#46]
Currently you have three icons, one for Intellij Idea, one for PyCharm, and one for PHPStorm. However, this theme doesn't have icons for many of the other Jetbrains IDES (CLion, Webstorm, etc...). It would be greatly appreciated if this could be implemented

**Comment by AGitBoy** [comment]
The full list of unthemed IDEs (with original icons attached):
* CLion
![Original Icon](https://images.g2crowd.com/uploads/product/image/large_detail/large_detail_1473786078/clion.png)

* DataGrip
![Original Icon](https://images.g2crowd.com/uploads/product/image/large_detail/large_detail_1510358728/datagrip.png)

* GoLand
![Original Icon](https://images.g2crowd.com/uploads/product/image/large_detail/large_detail_1513169944/goland.png)

* Rider
![Original Icon](https://pbs.twimg.com/profile_images/795623705091117058/lh1l265w.jpg)

* RubyMine
![Original Icon](https://confluence.jetbrains.com/download/attachments/20237/RUBYDEV?version=2&modificationDate=1449748395000&api=v2)

* WebStorm
![Original Icon](https://confluence.jetbrains.com/download/attachments/15797318/WI?version=2&modificationDate=1449749629000&api=v2)

**Comment by devmattrick** [comment]
Also might be worth adding one for [Jetbrains Toolbox](https://www.jetbrains.com/toolbox/app/).

**Comment by gusbemacbe** [comment]
@devmattrick 

JetBrains Toolbox does not have a desktop file or icons. How did you install it?

**Comment by gusbemacbe** [comment]
@AGitBoy and @devmattrick!

All the icons have been added to the [unstable branch](/gusbemacbe/suru-plus/tree/unstable). It will be merged into the master branch tomorrow.

**Comment by devmattrick** [comment]
Awesome thanks so much!

**Comment by AGitBoy** [comment]
Thanks, I really am liking the theme!
