### ISSUE TITLE
Invalid filenames, again

### ISSUE THREAD

**Issue by SmartFinn** [gusbemacbe/suru-plus#50]
## List of files with invalid filenames

The following files make impossible to create icon cache:

```
$ > gtk-update-icon-cache -f .
gtk-update-icon-cache: The generated cache was invalid.
```

- [x] apps/16/aptdaemon-download (2).svg
- [x] apps/16/games-app (1).svg
- [x] apps/16/org.gnome.Books (2).svg
- [x] apps/16/org.gnome.bijiben (1).svg
- [x] apps/16/picard (1).svg
- [x] apps/64/leafpad (1).svg
- [x] apps/symbolic/aptdaemon-download-symbolic (1).svg
- [x] apps/symbolic/games-app-symbolic (1).svg
- [x] apps/symbolic/picard-symbolic (1).svg

**Comment by gusbemacbe** [comment]
Read. Updated.

**Comment by gusbemacbe** [comment]
I have realised something wrong in my icons theme, i.e., for example, all the icons of power/session in KDE use the same icon, therefore, the original author built incorrectly and messed the icons, for example, some mimetypes icons are in the folder apps and some apps icons in the folders devices, mimetypes and places. I have to copy the folders apps, devices, mimetypes and places from Papirus to rebuild everything and to put end to all messes and all mistakes. I must work with all them this weekend.

**Comment by gusbemacbe** [comment]
For checking which icons are invalid, what are the commands?

**Comment by SmartFinn** [comment]
Check our [make test](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/tools/work/Makefile#L18) task, all of these commands are useful. Delete `-@` symbols before executing in a terminal, that's make's specific prefix.

**Comment by gusbemacbe** [comment]
I have fixed successfully the PKGBUILD. No invalid gtk-update-icon-cache. :-)
