### ISSUE TITLE
Mysql Workbench Icon

### ISSUE THREAD

**Issue by lapega** [gusbemacbe/suru-plus#53]
Hi!
Could you add the Mysql-workbench icon?
[icon](http://icons.iconarchive.com/icons/papirus-team/papirus-apps/512/mysql-workbench-icon.png)

Thanks!

**Comment by lapega** [comment]
(I just made the 16 and 64 px versions)

[mysql-workbench.zip](https://github.com/gusbemacbe/suru-plus/files/2492589/mysql-workbench.zip)

**Comment by gusbemacbe** [comment]
Hi @lapega 

You can fork my repository, upload these files and open a new pull request that I will merge into unstable branch. 

Do not forget of adding an icon in the `apps/symbolic` and of adding your name and your username in AUTHORS.

**Comment by lapega** [comment]
Ok, it will be my first time doing a fork.
I'll do my best.
Thx!
