### ISSUE TITLE
Unable of updating the branch

### ISSUE THREAD

**Issue by gusbemacbe** [gusbemacbe/suru-plus#58]
Hey @AGitBoy

I am unable of updating the branch, while merging into the master unstable, @AGitBoy.

1 - Back the files up
2 - Remove the repository
3 - SWitch to the branch unstable of my repository and fork
4 - Upload your backed up files
5 - Create the pull request and select the branch unstable.

**Comment by AGitBoy** [comment]
Followed your instructions and opened new PR https://github.com/gusbemacbe/suru-plus/pull/59
