### ISSUE TITLE
Flaticon license

### ISSUE THREAD

**Issue by jrnart** [gusbemacbe/suru-plus#64]
Any clarification on what the license is beyond CC-BY-SA and for what specific icons?

**Comment by gusbemacbe** [comment]
At Flaticon, **some** icons are under CC-BY-SA. The most of Flaticon icons are under Flaticon Basic Free License, and this licence is similar to CC-BY-SA. Both licences require attribution, therefore, I had to attribute Flaticon in each version. 

For example, you can see how the icons of Twitter are under  CC 3.0 BY at Flaticon: https://www.flaticon.com/packs/smileys-and-people-7

**Comment by JoshStrobl** [comment]
`CC-BY-SA` is not a valid SPDX 3.0 identifier. Are you referring to 2.0, 3.0, 4.0? It needs clarification.

**Comment by gusbemacbe** [comment]
Hi @JoshStrobl 

Too bad, as they are incompatible with GPL, I will remove them and replace for my own icons or Gravit icons (as I am Pro client, I am allowed to include them without attribution).

Please, sorry for my absence, I was very busy with my college, had to finish my heavier college jobs, but I am finished with the last two jobs.

I will return to the day 8 December to review the icons themes after finishing my last college job, introducing my thesis and getting graduated.

**Comment by JoshStrobl** [comment]
@gusbemacbe It's not a problem bud, we're all doing this with our own free time. Best of luck 👍

**Comment by gusbemacbe** [comment]
@JoshStrobl and @jrnart !

I have removed all Flaticon icons, and replaced for Gravit, Pixabay and OpenClipart icons, and I also created the icons from scratch. Some icons were inspired by Papirus. 

I have banned all Flaticon icons because I consider Flaticon the worst enemy of the Linux community and of the FOSS.
