### ISSUE TITLE
Possibility to remove the GSConnect (status bar) icon

### ISSUE THREAD

**Issue by pwd-github** [gusbemacbe/suru-plus#65]
I saw in issue #18 that this icon was added, but a giant G with an S in it, doesn't mean anything to me, I much prefer the default icon, is there any way to just remove this icon so I can fall back to the original?

**Comment by gusbemacbe** [comment]
Hi @pwd-github 

Sorry for my absence, I was very busy with my college, had to finish my heavier college jobs, but I am finished with the last two jobs.

I will return to the day 8 December to review the icons themes after finishing my last college job, introducing my thesis and getting graduated.

**Comment by pwd-github** [comment]
Congratulations @gusbemacbe. Take your time.

**Comment by gusbemacbe** [comment]
Thanks!

**Comment by gusbemacbe** [comment]
Hi @SmartFinn 

What is the name of this icon of GSConnect and what the folder?

I searched the whole repository.

**Comment by SmartFinn** [comment]
@gusbemacbe hi. It located there `symbolic/status/org.gnome.Shell.Extensions.GSConnect-symbolic.svg`

**Comment by gusbemacbe** [comment]
Thank you, @SmartFinn !

**Comment by gusbemacbe** [comment]
@pwd-github 

The icons have been removed from the branch `unstable-2`.

**Comment by pwd-github** [comment]
Thank you so much

**Comment by gusbemacbe** [comment]
@pwd-github, ready, official and released! The next release of Suru++ will be compatible with Oomox.

**Comment by pwd-github** [comment]
You're awesome @Gusbemacbe, thank you.

**Comment by gusbemacbe** [comment]
Hi @pwd-github 

You can see how the redesign of all 4,7 have been redesigned:

![image](https://user-images.githubusercontent.com/2257024/51788240-cceb6000-2162-11e9-8264-308bb93c5a96.png)

![image](https://user-images.githubusercontent.com/2257024/51788243-d674c800-2162-11e9-857e-54b67ea2bf2f.png)

![image](https://user-images.githubusercontent.com/2257024/51788248-dd9bd600-2162-11e9-97ce-6164f8459648.png)
