### ISSUE TITLE
No Icon for Focuswriter

### ISSUE THREAD

**Issue by mknepper** [gusbemacbe/suru-plus#66]
Missing the application icon for Gottcode's Focuswriter. Just thought I'd mention it.

**Comment by gusbemacbe** [comment]
Hi @mknepper 

Sorry for my absence, I was very busy with my college, had to finish my heavier college jobs, but I am finished with the last two jobs.

I will return to the day 8 December to review the icons themes after finishing my last college job, introducing my thesis and getting graduated.

**Comment by gusbemacbe** [comment]
Hi @mknepper !

The icon of Focus Writer has been added to the icon [unstable-2](/gusbemacbe/suru-plus/tree/unstable-2), but the small icon, not yet. 

I have increased the number of icons from 2,2k to 4,6k icons

**Comment by mknepper** [comment]
Awesome! You do great work. If you need help in the future, let me know!

**Comment by gusbemacbe** [comment]
Hi @mknepper, ready, official and released!

The next release of Suru++ will be like Papirus, for the support to Oomox.
