### ISSUE TITLE
Folder Icons color

### ISSUE THREAD

**Issue by reya276** [gusbemacbe/suru-plus#74]
Is it possible to change the Orange color to Blue? I have the suru++ icons which works great for light GTK3 themes. But if I set a dark theme then I can't change the folders to blue color.

**Comment by gusbemacbe** [comment]
Hi @reya276 

You can use my [Suru++ Folders](https://github.com/gusbemacbe/suru-plus-folders) to use the CLI to change one of 13 colours. 

As I am done with the college and got graduated, tomorrow I will begin to review and focus firstly on Suru++ 20 and the new version will come more new folder colours.

**Comment by gusbemacbe** [comment]
Hi @reya276 !


I inform you that [Suru++ Dark](/gusbemacbe/suru-plus-dark) has been upgraded and renamed to Suru++ 25 Dark. Check the screenshots: https://www.opendesktop.org/p/1245808/.

**Comment by reya276** [comment]
Oh awesome! Is there any place where I can leave a donation?

Rey Angeles

**Comment by gusbemacbe** [comment]
Hi @reya276 !

Paypal.me is not available in Brazil. But you can send by e-mail at PayPal. My e-mail is gusbemacbe at gmail dot com.

You also can pay tier as a donation at Patreon: https://www.patreon.com/gusbemacbe.
