### ISSUE TITLE
Wrong wastebin icon in Latte Dock

### ISSUE THREAD

**Issue by Omanggo** [gusbemacbe/suru-plus#76]
Hi

I encounter this litte problem, 56 px sized Suru++20 wastebin icon turn itself into papirus's wastebin icon (also happen when hover on it)

OS : Manjaro
DE : Plasma 5.14.4

Here a screenshot
![screenshot_20181219_235820](https://user-images.githubusercontent.com/45480650/50227860-aad32500-03e1-11e9-901a-72daf98af5ff.png)

Sorry for my painful english

**Comment by gusbemacbe** [comment]
I could not replicate it, the trash appeared as Suru++ trash icon on my laptop with Manjaro KDE 18.0 and on Latte Dock.

@SmartFinn, can you replicate it for us, please?

**Comment by SmartFinn** [comment]
@Omanggo try to delete icon cache and then restart Latte Dock:

```
rm -rf ~/.cache/ico* ~/.cache/plasm*
```

**Comment by Omanggo** [comment]
@SmartFinn I tried, give no effect

**Comment by gusbemacbe** [comment]
@Omanggo 

I have fixed the trash icons in the commit 53c8d53635653fab65401e90f07503162586b76b. I also have finished the small icons. Please use the branch `unstable-2` (remember it is unstable), and use Stacer to clean the icon caches, log out and log in.

**Comment by Omanggo** [comment]
@gusbemacbe 

Got it, Thanks!
