### ISSUE TITLE
Icon request : Transmageddon, Godot Engine, Deepin Music, MKVToolNix-GUI,  Persepolis Download Manager, Xtreme Download Manager

### ISSUE THREAD

**Issue by Omanggo** [gusbemacbe/suru-plus#77]
Hi

I love this project! really appreciate your hardwork.

And would be even better if you can create these icons

Please?

Program Name | Original Icon | Simple Description 
--------------------|------------------|-------------------------
Transmageddon | <img src="https://user-images.githubusercontent.com/45480650/50228774-b7f11380-03e3-11e9-871a-b41c5b080aea.png" width="128"> |  Video converter 
Godot Engine | ![Godot](https://godotengine.org/themes/godotengine/assets/logo.svg) | A 3D and 2D game engine
Deepin Music | <img src="https://user-images.githubusercontent.com/45480650/50230592-e53fc080-03e7-11e9-93ec-fc342fa9995e.png" width="128"> | Gorgeous & awesome music player!
MKVToolNix-GUI | <img src="https://assets.gitlab-static.net/uploads/-/system/project/avatar/4910441/mkvtoolnix-gui.png?width=64" width="128"> | Creating and working with Matroska files
Persepolis Download Manager | ![Persepolis](https://camo.githubusercontent.com/af3c72ead50c43c29b5aa5f10fdc6c1d26b720e8/68747470733a2f2f7065727365706f6c6973646d2e6769746875622e696f2f696d672f73637265656e2f7065727365706f6c6973d980726561646d652e706e67) | Persepolis is a Download Manager & a GUI For aria2
Xtreme Download Manager | <img src="https://user-images.githubusercontent.com/45480650/50231630-30f36980-03ea-11e9-935f-43e1389fd5b6.png" width="128"> | Powerfull download accelarator and video downloader

Thanks!

#Note : xdman is hardcoded icon, ignore it if you want

**Comment by gusbemacbe** [comment]
Hello @Omanggo!

What is your native language? I know 15 languages and I can assist you in any of 15 languages. 

Yes, I will create them in the branch [/gusbemacbe/suru-plus/tree/unstable-2] that will be merged in the official master branch. I just do not know when it will be ready. The unstable branch is in development for removing all the bugs that the original author could not solve in the frist version he built incorrectly.

**Comment by Omanggo** [comment]
Thank you for your reply

I speak Indonesian, what kind of assist you kindly offer? 

And thanks again, I'll wait patiently :)

**Comment by gusbemacbe** [comment]
Hi @Omanggo 

Unfortunately I do not speak Bahasa Indonesia yet. I used to study Bahasa Indonesia, but I stopped due to my college.

And all the icons, except Xtreme Downlaoder, have been added to the [unstable-2](/gusbemacbe/suru-plus/tree/unstable-2), but the small icons have not been done yet. 

The icon name of Xtreme Downloader, is it xdman?

**Comment by Omanggo** [comment]
Hallo, @gusbemacbe 

Thank you for your hardwork, glad to see them all.

And yes, it's xdman not xdm. (xdm stands for X display manager)

**Comment by gusbemacbe** [comment]
The con `xdman` has been added to 9fd417d. 

Here is the preview:

![xdman](https://user-images.githubusercontent.com/2257024/51585381-43b4fe80-1ec0-11e9-9b6e-2ff2275bf3b4.png)

**Comment by Omanggo** [comment]
Lovely, Thanks

**Comment by gusbemacbe** [comment]
@Omanggo , ready, official and released!

**Comment by Omanggo** [comment]
WOHOOOO!
