### ISSUE TITLE
Snap

### ISSUE THREAD

**Issue by sutterkaine75** [gusbemacbe/suru-plus#80]
Ciao, non capisco perchè gli snap non mi visualizza le icone belle.

Mi potete aiutare? Grazie mille!

**Comment by gusbemacbe** [comment]
Ciao @sutterkaine75 !

I temi di icone sono incompatibili con Snap perché i percorsi delle icone di applicazioni installate via Snap sono codificati fissamente (fissati e predefiniti, voglio dire, tu non puoi modificare modificarli). 

I file di configurazione di desktop di applicazioni dove puoi modificare i percorsi delle icone, sono fissamente inalterabili perché sono di proprietà del Snapcraft. 

Puoi solamente riprogramme, utilizzando un _hack_, come `sudo` per copiare i file di configurazione di desktop `/var/lib/snapd` per `$HOME/.local/applications/` e per rimuovere i file di configurazione di desktop dalla `var/lib/snapd` per evitare le duplicazioni. Dopo puoi modificare i percorsi delle icone sui file di desktop copiati. 

### Referenze

* https://github.com/keepassxreboot/keepassxc/issues/851
* https://forum.snapcraft.io/t/snaps-not-assuming-system-icon-themes/1767
