### ISSUE TITLE
Hey Sergey!

### ISSUE THREAD

**Issue by gusbemacbe** [gusbemacbe/suru-plus#81]
Hello @SmartFinn !

I would like to copy the folder `16` to the folder `symbolic`, but if I rename all files,including the symlinks, adding a suffix `-symbolic`, all the symlinks will be broken and unrecognised due to the nonexistence of the former files which do not have the suffix `-sylimk`. 

Is there a command line for this in terminal?

**Comment by SmartFinn** [comment]
Hi @gusbemacbe 

Rename all SVG files and symlinks:

```
rename.ul '.svg' -- '-symbolic.svg' *.svg
```

Remap symlinks targets:

```
rename.ul -s '.svg' -- '-symbolic.svg' *.svg
```

**Comment by SmartFinn** [comment]
Don't forget to delete all symlinks with symbolic suffix before renaming:

```
rm -f *-symbolic.svg
```

**Comment by gusbemacbe** [comment]
It worked, but few symlinks are broken due to containg `-`, `_`, `.` and `number`. I used `rename` instead of `rename.ul`.

**Comment by SmartFinn** [comment]
That's why I wrote the second comment. You need to delete `*-symbolic.svg` symlinks before.

**Comment by gusbemacbe** [comment]
Actually, I removed the folder `symbolic`, I copied the folder `16` whose icons have no suffix `-symbolic`, and pasted the folder, renaming `symbolic`.

**Comment by gusbemacbe** [comment]
Now it worked. Firstly I use KRename, then I ran `rename -s '.svg' -- '-symbolic.svg' *.svg`.

Thank you a lot!

**Comment by gusbemacbe** [comment]
@SmartFinn 

1. I saw you forked, but can I update the README and the CHANGELOG?
2. Can I upgrade other icons theme (Asprómauros, Dark and Telinkrin) if you have already forked Suru++?
3. I forgot of adding [Makefile](https://github.com/gusbemacbe/suru-plus/blob/v20.3.2/Makefile) file to this master branch. But is it important? It is for AUR Arch Linux.

**Comment by SmartFinn** [comment]
@gusbemacbe 

1. Sure. The merge has broken the fork so I recreated it.
2. Don't see any problem with it.
3. If you don't want to break AUR package you have to add it.
4. Wait for it. Oomox doesn't allow to create your own presets, especially gradients, so a separate script may be useful.

I do nothing for now. I wait for the release.

**Comment by SmartFinn** [comment]
@gusbemacbe ok. I'll start.

**Comment by gusbemacbe** [comment]
Hi @SmartFinn 

From `.svg` to `-symbolic.svg`, it works, but from `-symbolic.svg` to `.svg`, it does not work. See the problem that @Bonandry  is facing:

![image](https://user-images.githubusercontent.com/2257024/56351985-aa3a7780-61a4-11e9-8dc4-471c5a557757.png)

**Comment by SmartFinn** [comment]
@gusbemacbe the correct command is `rename.ul -s -- '-symbolic.svg' '.svg' *.svg`
