### ISSUE TITLE
KDE mediacontroller icon missed.

### ISSUE THREAD

**Issue by roachsinai** [gusbemacbe/suru-plus#88]
Seems there is no KDE mediacontroller plasmoid icon.

Use Papirus icon theme

![screenshot_20190130_123858](https://user-images.githubusercontent.com/9500049/51958677-063a0d80-248c-11e9-92dc-cca18a84ff89.png)

Use Suru icon theme

![screenshot_20190130_124019](https://user-images.githubusercontent.com/9500049/51958706-3681ac00-248c-11e9-91d5-345498a7abad.png)

**Comment by roachsinai** [comment]
I don't know does it beacause it doesn't exist in `breath` icon theme . I copy icon from `breeze` icon theme to `breath` and `Suru++` icon theme.

```
sudo cp /usr/share/icons/breeze/status/16/media-playback-* /usr/share/icons/breath/status/16/
sudo cp /usr/share/icons/breeze/status/22/media-playback-* /usr/share/icons/breath/status/22/
sudo cp /usr/share/icons/breeze/status/24/media-playback-* /usr/share/icons/breath/status/24/

sudo cp /usr/share/icons/breeze/status/16/media-playback-* /usr/share/icons/Suru++/status/16/
sudo cp /usr/share/icons/breeze/status/22/media-playback-* /usr/share/icons/Suru++/status/22/
sudo cp /usr/share/icons/breeze/status/24/media-playback-* /usr/share/icons/Suru++/status/24/
```

**Comment by gusbemacbe** [comment]
Thank you for reporting, I will add them.

**Comment by gusbemacbe** [comment]
Added icons. Preview in the 16 and 24:

![preview-mediaplayback](https://user-images.githubusercontent.com/2257024/52175727-47cdff80-278f-11e9-9014-f15e60e172aa.png)

**Comment by roachsinai** [comment]
May also no okular application icon which located at `apps/48/okular.svg` of breeze theme, too.

**Comment by gusbemacbe** [comment]
Hi @roachsinai!

The folder 48 is symlinked from the folder 64. It has already Okular icon. See the topic #38. It is a icon cache bug. Brave and Emacs are also affected. 

Not just Suru++, it also affected @palob's Numix icons theme. 

I recommend you to install @bilelmoussaoui's [StartupWMClassFixer](https://github.com/bilelmoussaoui/StartupWMClassFixer) and then to install [Stacer](https://github.com/oguzhaninan/Stacer) to clean all icon caches, to log out and log in.

**Comment by roachsinai** [comment]
Hi thanks for your recommendation! I didn't found `Suru++` icon for okular before. And now if I change icon size for task bar(panel) to 64 in icon settring, it shows.

**Comment by gusbemacbe** [comment]
Hi @roachsinai !

After installing and running StartupWNClassFixer and Stacer, did it work or not?

**Comment by roachsinai** [comment]
> Hi thanks for your recommendation! I didn't found `Suru++` icon for okular before. And now if I change icon size for task bar(panel) to 64 in icon settring, it shows.

As I wrote above, I had changed the system icon size and fixed okular icon. And to test `StartupWNClassFixer`, I revert my system icon size. And run `Fixer` showed me that:

`Fixed : Telegram`.

But `Telegram` icon shows always.
