### ISSUE TITLE
How change file manager icon?

### ISSUE THREAD

**Issue by AdsonCicilioti** [gusbemacbe/suru-plus#89]
For any these, except the second (that is default)?
![image](https://github.com/gusbemacbe/suru-plus/raw/master/images/preview5.png)

**Comment by gusbemacbe** [comment]
Click here - clique aqui - faz um clic nisto

<details>
<summary>English</summary>
Hi @AdsonCicilioti !

You can change icon name by middle of `Icon=...` in the desktop files (`.desktop`) at the folder `/usr/share/applications/`. Remember that you need to run as `sudo` to modify the desktop files. 
</details>

<details>
<summary>Português brasileiro</summary>
Olá @AdsonCicilioti !

Você pode mudar o nome do ícone por meio de `Icon=...` nos arquivos de configuração de desktop (`.desktop`) na pasta `/usr/share/applications/`. Lembre-se que você precisa entrar como `sudo` para editar os arquivos de desktop.
</details>

<details>
<summary>Português europeu</summary>
Olá @AdsonCicilioti !

Podes modificar o nome do ícone com `Icon=...` nos ficheiros de configuração de desktop (`.desktop`) no directório `/usr/share/applications/`. Lembra-te que tu deves executar como `sudo` para modificar os ficheiros de desktop.
</details>

**Comment by nealot** [comment]
Hi @gusbemacbe, your last update was terrific! I was wondering if the default icon for nautilus/gnome-files can be changed to something similar to the 4th icon pictured above? I'm having a little trouble adjusting to it because the white and blue background make it difficult to distinguish.

**Comment by gusbemacbe** [comment]
Hi @nealot !

Go to the file `nautilus.desktop` or `org.gnome.nautilus.desktop` at the folder `/usr/share/applications', run as `sudo` and change `Icon=...` to any of these:

* `Icon=file-manager`
* `Icon=caja`
* `Icon=nautilus`
* `Icon=nemo`
* `Icon=sapcefm-find`
* `Icon=thunar` 

Remember that if you make an upgrade of your system, these desktop files will revert to the original icon name. I am not sure of how to prevent only these desktop files from being modified and reverted by the system upgrade. Maybe @SmartFinn is an user of Ubuntu and must know something.

**Comment by AdsonCicilioti** [comment]
Ah abençoado!! Tu é pt_BR (@gusbemacbe ).. Bom trabalho man!
Oh Blessed! You are pt_BR... Good work men!

**Comment by AdsonCicilioti** [comment]
I make a copy from `/usr/share/applications/.....nautilus.desktop` to `~/.local/share/applications/`.. Better to manage!

Thanks!
