### ISSUE TITLE
XFCE Whisker menu icons

### ISSUE THREAD

**Issue by darcn181** [gusbemacbe/suru-plus#90]
The icons for exiting session and the ones next to it look really weird on the whisker menu they need a redesign in my opinion and there's a missing icon for favorites, and When will you update the dark version of suru?
![image](https://user-images.githubusercontent.com/28988467/52099665-7dfe5a00-25aa-11e9-9bad-772d85e9f1d5.png)

**Comment by gusbemacbe** [comment]
Hello @darcn181 !

Please test Papirus if it appears OK.

**Comment by gusbemacbe** [comment]
<details>
<summary>English</summary>

Once I redesign all the devices and mimetypes icons, I will upgrade the Dark version

</details>

<details>
<summary>Español</summary>
Una vez que terminaré de rediseñar todos los íconos de las carpetas `devices` y `mimetypes`, voy a hacer _upgrade_ de la versión Oscura. 
</details>

**Comment by darcn181** [comment]
I use Papirus all the time and it's displayed correctly there, Forgot to say that i use xfce4-gtk3, it's preinstalled in new versions of manjaro

Uso Papirus todo el tiempo y todo se ve correcto ahi, Olvide decir que uso xfce4-gtk3, viene preinstalado en nuevas versiones de manjaro

**Comment by gusbemacbe** [comment]
Hi @SmartFinn!

I used Meld to compare the places icons of Papirus and Suru++, but I did not find the icon of favourites in XFCE Whisker.

**Comment by SmartFinn** [comment]
@gusbemacbe it's `user-bookmarks`

**Comment by gusbemacbe** [comment]
I have tested. Here is how:
He provado. Aquí está como:

![whisker](https://user-images.githubusercontent.com/2257024/52204436-44a04580-285b-11e9-9d42-7c3766d7c8e1.png)

If you want to install the beta branch instead, here: 
Si quieres instalar la branch beta, aquí está:

```
wget -qO- https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/install.sh | TAG=beta sh
```

**Comment by darcn181** [comment]
![image](https://user-images.githubusercontent.com/28988467/52249050-8c5cb680-28c7-11e9-9bc3-f0a28f3499cc.png)
Everything looks good now, but i still think that the log out and others icons should get a redesign they just don't look as good as the other ones.

why not make a script for changing the color of the symbolic icons?, this way you can keep maintining the icon theme without having to worry of changing all the icons color, making a file for the list of icon that needs a change in color, and a script that would read the name's in that list and change the color of the svg files using text editing magic.

**Comment by gusbemacbe** [comment]
Hi @darcn181 !

> Everything looks good now, but i still think that the log out and others icons should get a redesign they just don't look as good as the other ones.

Do you mean the orange icon of log out, the golden icon of user and the other icons of sessions?

> why not make a script for changing the color of the symbolic icons?, this way you can keep maintining the icon theme without having to worry of changing all the icons color, making a file for the list of icon that needs a change in color, and a script that would read the name's in that list and change the color of the svg files using text editing magic.

The latest version of `master` of Suru++ is already compatible with @actionless's [Oomox](https://github.com/themix-project/oomox) and it allows you to replace the colour of all small icons and of folders with any colour you want.

**Comment by darcn181** [comment]
Yes, those were the icons i was talking about. Seems i'll give oomox a try with your icon set

**Comment by gusbemacbe** [comment]
Hi @darcn181 !

> Yes, those were the icons i was talking about.

Let me understand. Are you suggesting these session icons be monochromatic.

Well, KDE requires the icons of 24px to be colourful in the KDE System Settings, so icons of 24px are symlinked from the icons of 64px. Some KDE users complained about the monochromatic icons of 24px in KDE System Settings and wanted them to colourful like 64px icons. Arch Linux GNOME and Ubuntu users also complained. 

If you suggest the monochrome of 24px icons, the ideal is to separate each theme for each environment, one for all desktop environments and another, but very small, for XFCE, like I did with Lubuntu. I think the next upgrade of Suru++ Lubuntu will fit well with XFCE. 

But I would like to hear the opinion of @SmartFinn about this idea. 

You can speak in Spanish if you want. I have studied Spanish since 9 years old.

**Comment by darcn181** [comment]
I'd prefer that this issue stays in english since that's the most talked language in my opinion, so more people can read it.

I think that these icon should not be monochrome because they would kill the uniformity with the ones that are for the categories like games. What i think is that they should be redesigned in color and change the symbols a little bit so they are more uniform, for example, the change user icon is a realistic silhouette while the other ones have a tendency to be rounded like the log out and power off button.

I'm gonna try make some redesigns and post them here.

Oh and i made a sublime-text redesign, you can add it to the icon set if you want but i couldn't quite recreate the rounded form that the icons have.
[Sublime.tar.gz](https://github.com/gusbemacbe/suru-plus/files/2833806/Sublime.tar.gz)

**Comment by darcn181** [comment]
![image](https://user-images.githubusercontent.com/28988467/52306485-8241c300-296e-11e9-9092-ae7023594184.png)
Here's what i got, haven't remade all icons but looks better now.
[Icons.tar.gz](https://github.com/gusbemacbe/suru-plus/files/2834066/Icons.tar.gz)

**Comment by gusbemacbe** [comment]
Hi @darcn181 !

Sorry for my absence, because I was called for the graduation commemoration with my family after yesterday I got graduated in a university graduation ceremony. 

> Oh and i made a sublime-text redesign, you can add it to the icon set if you want but i couldn't quite recreate the rounded form that the icons have.
[Sublime.tar.gz](https://github.com/gusbemacbe/suru-plus/files/2833806/Sublime.tar.gz)

Your icon is better than mine. But it needs to be readjusted to work in KDE, because in your XFCE or any GTK-based, the icon appears with yellow background and with black letter, while in KDE, everything appears yellow. 

> Here's what i got, haven't remade all icons but looks better now.
[Icons.tar.gz](https://github.com/gusbemacbe/suru-plus/files/2834066/Icons.tar.gz)

Better now, I will apply your icons to default icons and create the alternative icons that the user can choice. 

I will readjust some other session icons, according to your redesign.

**Comment by darcn181** [comment]
Well i can't test the icon on KDE because i use a netbook and KDE's performance is just not acceptable.
I'm still gonna try redesign session icons and then we can see which ones are better for the theme, i thought that the icons shouldn't have a monochrome or almost de-saturated gradients, it just screams cyberpunk with the bright colors.

**Comment by actionless** [comment]
> redesign session icons

what about swaping black and color parts places? what icons will be colorful with black accents

**Comment by gusbemacbe** [comment]
Hi @darcn181 !

> Well i can't test the icon on KDE because i use a netbook and KDE's performance is just not acceptable.

You can install Dolphin in XFCE without installing KDE. Dolphin is QT-based file manager, it can reveal how the icons are like in KDE. 

> i thought that the icons shouldn't have a monochrome or almost de-saturated gradients, it just screams cyberpunk with the bright colors.

Do you mean the 16px icons?

**Comment by darcn181** [comment]
I'm gonna test the icon in dolphin. So this is Qt related only right?
What i meant is that when i think of cyberpunk, i think of bright colors on dark settings just like blade runner and in concept art of cyberpunk 2077 so that's why i went with dark icons this time and i don't mean that all 16px icons should look like this, this is just me explaining the style of the icons and even so those icons are actually 64 AFAIK, XFCE just fixes their size to 16px, speaking of the green icon, i don't know if i should fix that icon, maybe if i make other icons look similar to that one i think everything would look nice

**Comment by darcn181** [comment]
It seems that the icon is displayed correctly here
![image](https://user-images.githubusercontent.com/28988467/52318347-6522e980-299a-11e9-9764-4453cc411aba.png)

**Comment by gusbemacbe** [comment]
> Oh and in the project front page you have a typo
"Suru++ 25 — A cyberpunk, elegant, **futuirtisc** and modern third-party icons theme"
It should be futuristic

AH, thank you for reporting.

Strange, in my Dolphin:

![image](https://user-images.githubusercontent.com/2257024/52318411-86400600-29ab-11e9-8e69-1556218ff476.png)

But, do not worry, I know to fix it.

**Comment by gusbemacbe** [comment]
Now it is fixed:

![image](https://user-images.githubusercontent.com/2257024/52318735-05820980-29ad-11e9-9f8f-bddb44a48e8a.png)

**Comment by darcn181** [comment]
Now that i see that sublime-text-alt icon, i think you should just swap out the gradients, the S becomes yellow and the background black, just like the original.

**Comment by gusbemacbe** [comment]
Hi @darcn181 ! 

I am confused. To the icon sublime-text-alt.svg or sublime-text.svg with new gradients?

**Comment by darcn181** [comment]
To sublime-text-alt.svg, and please wait until i redesign all icons, i've changed them a little bit

**Comment by darcn181** [comment]
Which one do you think looks the best?
![image](https://user-images.githubusercontent.com/28988467/52320051-46752080-29a3-11e9-892e-f809f775f0a2.png)
![image](https://user-images.githubusercontent.com/28988467/52320061-6573b280-29a3-11e9-8721-b93d5f5933c8.png)

**Comment by gusbemacbe** [comment]
The second.

**Comment by darcn181** [comment]
Here's how the whisker menu looks now, i still need to add the glow to some icons
![image](https://user-images.githubusercontent.com/28988467/52320157-1ed28800-29a4-11e9-9448-f50fe7bd7079.png)

**Comment by gusbemacbe** [comment]
OK, do not forget to test with dark mode of this menu, to distinguish the back tones.

**Comment by darcn181** [comment]
What do you think good to go?
Adapta
![image](https://user-images.githubusercontent.com/28988467/52320523-1ed38780-29a6-11e9-9029-721ad303fc69.png)

Matcha
![image](https://user-images.githubusercontent.com/28988467/52320581-91446780-29a6-11e9-8236-104fc19a68b7.png)

**Comment by gusbemacbe** [comment]
Now better.

**Comment by darcn181** [comment]
Here are all the files, give them a test before uploading them
[Icons.tar.gz](https://github.com/gusbemacbe/suru-plus/files/2834911/Icons.tar.gz)

**Comment by gusbemacbe** [comment]
See if it is better for you. I liked all the icons, but I also created the alternative icons and allow the user to choose the icons.

**Comment by gusbemacbe** [comment]
I updated README. See https://github.com/gusbemacbe/suru-plus/tree/beta#alternative-session-icons.

**Comment by darcn181** [comment]
I really like that you made alt icons so people can change them. But i think you should not mention the sublime text in the alternative session icons because it's not but if you make more alt icons you can mention it in there
![imagen](https://user-images.githubusercontent.com/28988467/52349019-02fad080-29fc-11e9-81aa-a52a67c08ca1.png)

**Comment by gusbemacbe** [comment]
Hi @darcn181 !

Thank you for reporting, I will correct.

**Comment by gusbemacbe** [comment]
Hi @darcn181 !

I have just released. You have been credited in the screenshot and in the details at OpenDesktop: https://www.opendesktop.org/p/1238162/

**Comment by darcn181** [comment]
Thanks for the credit!, if you ever need some help just tell me and i'll see what i can do.

**Comment by gusbemacbe** [comment]
You are welcome. I would like to ask you. Are you developer/programmer?

**Comment by darcn181** [comment]
No, i always wanted to learn how to program but my pc's performance didn't make it easy to me but because of it i learned how to design things even though i took a break from it for around 2 years.

**Comment by gusbemacbe** [comment]
HI @darcn181 !


I inform you that [Suru++ Dark](/gusbemacbe/suru-plus-dark) has been upgraded and renamed to Suru++ 25 Dark. Check the screenshots: https://www.opendesktop.org/p/1245808/.
