### ISSUE TITLE
Adjustments to KDE in dark Plasma subjects

### ISSUE THREAD

**Issue by AndrealeDicam** [gusbemacbe/suru-plus#91]
A very special greeting and I must thank you for the impressive work on this pack of icons that are now my favorites. Only one concern, the symbolic icons in dark plasma themes invoked from Alt + F2 are not well visualized. They fail to stand out with a light tone and get lost. They only work with clear themes. Thank you very much for your help and I wish you the best of luck.

NOTE: I use KDE Neon, with Plasma 5.14.5, KDE Frameworks 5.54.0, Qt 5.12, Kernel 4.15.0.45.

![screenshot_20190208_121635](https://user-images.githubusercontent.com/30961489/52495643-5b1e0800-2b9f-11e9-9193-32b6f5fff777.png)

![screenshot_20190208_122034](https://user-images.githubusercontent.com/30961489/52495667-6d984180-2b9f-11e9-9eaa-4391911d538e.png)

**Comment by gusbemacbe** [comment]
Hi @AndrealeDicam !

As Suru++'s new version that I have just released today, is officially compatible with @actionless's Oomox, then you can change the colour of all small icons and of folders with any colour you to fit with your dark KDE environment.

**Comment by gusbemacbe** [comment]
Hi @AndrealeDicam !

I inform you that [Suru++ Dark](/gusbemacbe/suru-plus-dark) has been upgraded and renamed to Suru++ 25 Dark. Check the screenshots: https://www.opendesktop.org/p/1245808/. 

If you are satisfied with it, please close the issue.

**Comment by AndrealeDicam** [comment]
Hello, thank you very much for informing me about this package of light icons for dark environments. They are beautiful and I didn't realize their existence, I thought there were only the traditional ones since the Suru++ 25 project page doesn't mention them. A big thank you hug.
