### ISSUE TITLE
Suru++ falls back to Adwaita

### ISSUE THREAD

**Issue by materemias** [gusbemacbe/suru-plus#94]
I had Suru installed from git, now that the AUR package got upated I wanted to switch back to the package maintained version so I deleted /usr/share/icon/Suru++ and installed from AUR 25.1
If i pick Suru++ as icons in gnome tweaks it seemingly loads but the icons are adwaita instead of suru. i have tried uninstalling, reinstalling from git, etc still suru seems to not load any more. Any ideas how to fix this?

**Comment by gusbemacbe** [comment]
Hi @materemias !

I am investigating the bug in Ubuntu in the moment, and then in GNOME Arch-based distro. 

Please select Suru++, and open the terminal, run the command `nautilus`, you will receive the warning about icons theme.

**Comment by gusbemacbe** [comment]
I found a bug now. 

It is in the theme `index.theme`, which missed `=` in the Greek translation.

**Comment by gusbemacbe** [comment]
Please see if it works for you with the update.

**Comment by materemias** [comment]
it is ok now, thanks
