### ISSUE TITLE
Icon for todour.

### ISSUE THREAD

**Issue by roachsinai** [gusbemacbe/suru-plus#98]
I install a todo software [todour](https://github.com/SverrirValgeirsson/Todour). Would you please add the ico?

**Comment by gusbemacbe** [comment]
HI @roachsinai !

I tried to find the Todour icon. It seems that the app does not have icon. 
Therefore, I had to download the macOS app to find the ICNS file.

**Comment by roachsinai** [comment]
There it is. https://github.com/SverrirValgeirsson/Todour/blob/master/newicon.png

**Comment by gusbemacbe** [comment]
Thank you, @roachsinai ! I have already added an icon 3 hours ago, it is very similar to this icon you cited above.

But you need to change "newicon" to "todour" in the desktop file at `/usr/share/applications`, because this path is hardcoded.

**Comment by roachsinai** [comment]
Thanks a lot.

**Comment by gusbemacbe** [comment]
Use the branch `beta` if you need that icon. I did not merge to the branch `master` yet. 

Observe that you can change the gradient colours of 16px icons with your favourite colours, using Oomox or choose one of 9 gradient colours, using [Suru++ Colourise](/gusbemacbe/suru-plus-colourise). Check the [v25.2.0 at README](https://github.com/gusbemacbe/suru-plus/tree/beta#version-2520).

**Comment by roachsinai** [comment]
That's awesome!
