### ISSUE TITLE
[Request] KDE Konsole icons black & VNC Viewer

### ISSUE THREAD

**Issue by akha666** [gusbemacbe/suru-plus#99]
Really nice Icons I have ever installed on my all desktops, 
Please:-
1- make KDE Konsole icons black. the current version has the same color as Dolphin file manager.
2- VNC Viewer https://www.realvnc.com/en/connect/download/viewer/
thank you

**Comment by gusbemacbe** [comment]
HI @akha666 !

Please, can you take a screenshot of how Konsole is now? My Konsole is all OK.

**Comment by akha666** [comment]
Thank you for your quick reponse,
![screenshot_20190305_150855](https://user-images.githubusercontent.com/28590461/53860333-4b9cae00-3fe9-11e9-850a-5b2441650bf3.png)
![screenshot_20190305_150033](https://user-images.githubusercontent.com/28590461/53860344-522b2580-3fe9-11e9-9a0d-6ab33e134580.png)

**Comment by gusbemacbe** [comment]
HI @akha666 !

For Dolphin, you can check the [Changing the file manager icon](https://github.com/gusbemacbe/suru-plus#file-manager-icon) and change `file-manager` to `dolphin`.

For Konsole, Konsole is a generic icon, as GNOME Terminal, XFCE Terminal are. You need to modify manually the desktop file of Konsole and choose one of any terminal icons, as Deepin Terminal's, etc. But I will reconsider adding the new alternative icons, with the help of darcn181.

**Comment by akha666** [comment]
Hello @gusbemacbe !
Nice workaround, I changed my Konsole icon to utilities-x-terminal, and it looks very cool.
Thank you,

**Comment by gusbemacbe** [comment]
You are welcome, and as you solved, I close the issue.
